version: '3.7'

services:
  katsu-db:
    image: postgres:13-alpine
    container_name: katsu-db
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    expose:
      - 5432
    volumes:
      - ./tmp:/var/lib/postgresql/data