version: '3.7'

services:
  katsu-db:
    image: postgres:13-alpine
    container_name: katsu-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    container_name: katsu_adminer
    restart: always
    ports:
      - 8080:8080