[flake8]
max-line-length = 120
exclude = .git, .tox, __pycache__, migrations, chord_metadata_service/vrs

[testenv]
passenv =
    CHORD_*
    POSTGRES_*
skip_install = true
allowlist_externals =
    poetry
commands =
    poetry sync
    poetry run coverage run --branch ./manage.py test
    poetry run coverage html
    poetry run flake8 ./chord_metadata_service
    poetry run ruff check ./chord_metadata_service
