# Generated by Django 4.1.1 on 2023-02-01 23:59

import chord_metadata_service.mohpackets.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "submitter_donor_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("is_deceased", models.BooleanField()),
                (
                    "cause_of_death",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_of_birth", models.CharField(max_length=32)),
                (
                    "date_of_death",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "primary_site",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
            ],
            options={
                "ordering": ["submitter_donor_id"],
            },
        ),
        migrations.CreateModel(
            name="PrimaryDiagnosis",
            fields=[
                (
                    "submitter_primary_diagnosis_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("date_of_diagnosis", models.CharField(max_length=32)),
                ("cancer_type_code", models.CharField(max_length=64)),
                ("basis_of_diagnosis", models.CharField(max_length=128)),
                ("lymph_nodes_examined_status", models.CharField(max_length=128)),
                ("lymph_nodes_examined_method", models.CharField(max_length=64)),
                (
                    "number_lymph_nodes_positive",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "clinical_tumour_staging_system",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "clinical_t_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "clinical_n_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "clinical_m_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "clinical_stage_group",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "ordering": ["submitter_primary_diagnosis_id"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "program_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated",
                    chord_metadata_service.mohpackets.models.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["program_id"],
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "submitter_specimen_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "pathological_tumour_staging_system",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pathological_t_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "pathological_n_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "pathological_m_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "pathological_stage_group",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("specimen_collection_date", models.CharField(max_length=32)),
                ("specimen_storage", models.CharField(max_length=64)),
                (
                    "tumour_histological_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "specimen_anatomic_location",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reference_pathology_confirmed_diagnosis",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reference_pathology_confirmed_tumour_presence",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "tumour_grading_system",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tumour_grade",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "percent_tumour_cells_range",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "percent_tumour_cells_measurement_method",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_primary_diagnosis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.primarydiagnosis",
                    ),
                ),
            ],
            options={
                "ordering": ["submitter_specimen_id"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "submitter_treatment_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "treatment_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("is_primary_treatment", models.CharField(max_length=32)),
                ("treatment_start_date", models.CharField(max_length=32)),
                ("treatment_end_date", models.CharField(max_length=32)),
                ("treatment_setting", models.CharField(max_length=128)),
                ("treatment_intent", models.CharField(max_length=128)),
                (
                    "days_per_cycle",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_cycles",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "response_to_treatment_criteria_method",
                    models.CharField(max_length=255),
                ),
                ("response_to_treatment", models.CharField(max_length=255)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_primary_diagnosis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.primarydiagnosis",
                    ),
                ),
            ],
            options={
                "ordering": ["submitter_treatment_id"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("surgery_type", models.CharField(max_length=255)),
                (
                    "surgery_site",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "surgery_location",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tumour_length",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tumour_width",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "greatest_dimension_tumour",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tumour_focality",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "residual_tumour_classification",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "margin_types_involved",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=128
                        ),
                        size=None,
                    ),
                ),
                (
                    "margin_types_not_involved",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=128
                        ),
                        size=None,
                    ),
                ),
                (
                    "margin_types_not_assessed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=128
                        ),
                        size=None,
                    ),
                ),
                (
                    "lymphovascular_invasion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "perineural_invasion",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_specimen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.specimen",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SampleRegistration",
            fields=[
                (
                    "submitter_sample_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("gender", models.CharField(max_length=32)),
                ("sex_at_birth", models.CharField(max_length=32)),
                ("specimen_tissue_source", models.CharField(max_length=255)),
                ("tumour_normal_designation", models.CharField(max_length=32)),
                ("specimen_type", models.CharField(max_length=255)),
                ("sample_type", models.CharField(max_length=128)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_specimen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.specimen",
                    ),
                ),
            ],
            options={
                "ordering": ["submitter_sample_id"],
            },
        ),
        migrations.CreateModel(
            name="Radiation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("radiation_therapy_modality", models.CharField(max_length=255)),
                ("radiation_therapy_type", models.CharField(max_length=64)),
                ("radiation_therapy_fractions", models.PositiveSmallIntegerField()),
                ("radiation_therapy_dosage", models.PositiveSmallIntegerField()),
                ("anatomical_site_irradiated", models.CharField(max_length=255)),
                ("radiation_boost", models.BooleanField(null=True)),
                (
                    "reference_radiation_treatment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="primarydiagnosis",
            name="program_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mohpackets.program"
            ),
        ),
        migrations.AddField(
            model_name="primarydiagnosis",
            name="submitter_donor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mohpackets.donor"
            ),
        ),
        migrations.CreateModel(
            name="Immunotherapy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("immunotherapy_type", models.CharField(max_length=255)),
                ("drug_name", models.CharField(max_length=255)),
                ("drug_rxnormcui", models.CharField(max_length=64)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HormoneTherapy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drug_name", models.CharField(max_length=255)),
                ("drug_rxnormcui", models.CharField(max_length=64)),
                ("hormone_drug_dosage_units", models.CharField(max_length=64)),
                (
                    "cumulative_drug_dosage_prescribed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cumulative_drug_dosage_actual",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "submitter_follow_up_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("date_of_followup", models.CharField(max_length=32)),
                ("lost_to_followup", models.BooleanField(null=True)),
                (
                    "lost_to_followup_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("disease_status_at_followup", models.CharField(max_length=255)),
                (
                    "relapse_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "date_of_relapse",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "method_of_progression_status",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "anatomic_site_progression_or_recurrence",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "recurrence_tumour_staging_system",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "recurrence_t_category",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "recurrence_n_category",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "recurrence_m_category",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "recurrence_stage_group",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_primary_diagnosis_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.primarydiagnosis",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["submitter_follow_up_id"],
            },
        ),
        migrations.AddField(
            model_name="donor",
            name="program_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mohpackets.program"
            ),
        ),
        migrations.CreateModel(
            name="Comorbidity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prior_malignancy", models.CharField(max_length=32)),
                (
                    "laterality_of_prior_malignancy",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "age_at_comorbidity_diagnosis",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "comorbidity_type_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "comorbidity_treatment_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "comorbidity_treatment",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Chemotherapy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drug_name", models.CharField(max_length=255)),
                ("drug_rxnormcui", models.CharField(max_length=64)),
                ("chemotherapy_dosage_units", models.CharField(max_length=64)),
                (
                    "cumulative_drug_dosage_prescribed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cumulative_drug_dosage_actual",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Biomarker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "test_interval",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("psa_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ca125", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cea", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.program",
                    ),
                ),
                (
                    "submitter_donor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mohpackets.donor",
                    ),
                ),
                (
                    "submitter_follow_up_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.followup",
                    ),
                ),
                (
                    "submitter_primary_diagnosis_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.primarydiagnosis",
                    ),
                ),
                (
                    "submitter_specimen_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.specimen",
                    ),
                ),
                (
                    "submitter_treatment_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mohpackets.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
