# Generated by Django 5.2.8 on 2026-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='primarydiagnosis',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sampleregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specimen',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treatment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_donor_id'), name='unique_donor'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_follow_up_id'), name='unique_follow_up'),
        ),
        migrations.AddConstraint(
            model_name='primarydiagnosis',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_primary_diagnosis_id'), name='unique_primary_diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='sampleregistration',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_sample_id'), name='unique_sample_registration'),
        ),
        migrations.AddConstraint(
            model_name='specimen',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_specimen_id'), name='unique_specimen'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(fields=('program_id', 'submitter_treatment_id'), name='unique_treatment'),
        ),
    ]
