# Generated by Django 4.2.3 on 2023-11-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0002_alter_primarydiagnosis_donor_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposure',
            options={'ordering': ['uuid']},
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('program_id', 'submitter_donor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together={('program_id', 'submitter_follow_up_id')},
        ),
        migrations.AlterUniqueTogether(
            name='primarydiagnosis',
            unique_together={('program_id', 'submitter_primary_diagnosis_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sampleregistration',
            unique_together={('program_id', 'submitter_sample_id')},
        ),
        migrations.AlterUniqueTogether(
            name='specimen',
            unique_together={('program_id', 'submitter_specimen_id')},
        ),
        migrations.AlterUniqueTogether(
            name='treatment',
            unique_together={('program_id', 'submitter_treatment_id')},
        ),
    ]
