# Generated by Django 4.2.3 on 2023-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0003_alter_exposure_options_alter_donor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='submitter_primary_diagnosis_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='submitter_treatment_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
