# Generated by Django 5.1.8 on 2025-05-21 18:18

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_v11_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='extra_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Extra properties that do not have a predefined field in the database.', validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator({'$id': 'https://bentov2.local/api/metadata/api/schemas/phenopacket/extra_properties', '$schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'}, formats=None)]),
        ),
    ]
