# Generated by Django 5.1.11 on 2025-07-31 19:40

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_geolocation_extra_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='extra_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Extra properties that do not have a predefined field in the database.', validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='EXTRA_PROPERTIES_SCHEMA')]),
        ),
    ]
