import re

from bento_lib.discovery import (
    DiscoveryConfig,
    DateFieldDefinition,
    FieldDefinition,
    NumberFieldDefinition,
    StringFieldDefinition,
    OntologyClassFieldDefinition,
    DiscoveryEntity,
)
from bento_lib.ontologies.models import CURIE_PATTERN, OntologyClass
from collections import Counter, defaultdict
from functools import wraps

from chord_metadata_service.discovery.censorship import get_threshold
from django.db.models import Case, CharField, Count, F, Func, IntegerField, QuerySet, When, Value, Q, Exists, OuterRef
from django.db.models.functions import Cast
from structlog.stdlib import BoundLogger
from typing import Literal, Callable

from chord_metadata_service.authz.types import DataPermissions

from . import fields_utils as f_utils
from .censorship import censor_count, thresholded_count
from .field_paths.django_field_query import DiscoveryFieldSubquery, get_field_django_mapping_and_queried_entity
from .scope import ValidatedDiscoveryScope
from .pydantic_models import BinWithValue, BinList, DiscoveryQueryFilterOneOf
from .stats import queryset_stats_for_field
from .utils import get_discovery_entity_model_scoped_queryset

LENGTH_Y_M = 4 + 1 + 2  # dates stored as yyyy-mm-dd

# Re-usable regex components
P_MAX_SYM = r"(?P<sym>[<≤])"
P_MIN_SYM = r"(?P<sym>[>≥])"
P_START_SYM = r"(?P<start_sym>[\[(>≥])"
P_END_SYM = r"(?P<end_sym>[])<≤])"
P_NUMBER = r"-?\d+(\.\d+)?"
P_DATE = r"\d{4}(-\d{2}(-\d{2})?)?"
P_DATE_EXACT = r"\d{4}-\d{2}-\d{2}"

# CURIE compiled pattern
P_CURIE = re.compile(CURIE_PATTERN)

# Number range patterns
#  - Number range patterns
P_NUMBER_MAX_VALUE = re.compile(rf"{P_MAX_SYM} ?(?P<val>{P_NUMBER})")
P_NUMBER_RANGE = re.compile(rf"{P_START_SYM}(?P<start>{P_NUMBER}), ?(?P<end>{P_NUMBER}){P_END_SYM}")
P_NUMBER_MIN_VALUE = re.compile(rf"{P_MIN_SYM} ?(?P<val>-?\d+(\.\d+)?)")
#  - Exact number pattern
P_NUMBER_EXACT_VALUE = re.compile(rf"(?P<val>{P_NUMBER})")

# Date patterns
#  - Date bin pattern: machine-readable "yyyy-mm" bin key, as generated by labelled_date_range_generator_by_month
P_DATE_BIN = re.compile(r"\d{4}-\d{2}\Z")
#  - Date range patterns
P_DATE_MAX_VALUE = re.compile(rf"{P_MAX_SYM} ?(?P<val>{P_DATE})")
P_DATE_RANGE = re.compile(rf"{P_START_SYM}(?P<start>{P_DATE}), ?(?P<end>{P_DATE}){P_END_SYM}")
P_DATE_MIN_VALUE = re.compile(rf"{P_MIN_SYM} ?(?P<val>{P_DATE})")
#  - Exact date patterns (Y-M-D)
P_DATE_EXACT_VALUE = re.compile(rf"(?P<val>{P_DATE_EXACT})")


def field_value_is_in_options(
    value: str | DiscoveryQueryFilterOneOf,
    options: frozenset[str] | frozenset[OntologyClass],
    ft: Literal["string", "ontology-class", "number", "date"],
) -> bool:
    """
    Whether a field value matches any of the pre-determined options (usually for censored discovery). If the field type
    is a string, the comparison is case-insensitive.
    """
    if isinstance(value, DiscoveryQueryFilterOneOf):
        return all(field_value_is_in_options(v, options, ft) for v in value.values)
    if ft == "string":
        return any(value.casefold() == o.casefold() for o in options)
    elif ft == "ontology-class":
        return any(value.casefold() == (o.id if isinstance(o, OntologyClass) else o).casefold() for o in options)
    return value in options


def map_if_multi_value_filter(func: Callable[[str], bool]) -> Callable[[str | DiscoveryQueryFilterOneOf], bool]:
    """
    Decorator for filter format checker functions. If the value is a DiscoveryQueryFilterOneOf, the inner function will
    be mapped over the inner values; otherwise, it'll transparently check the format of a single value string.
    """
    @wraps(func)
    def inner(value: str | DiscoveryQueryFilterOneOf) -> bool:
        if isinstance(value, DiscoveryQueryFilterOneOf):
            return all(map(func, value.values))
        return func(value)
    return inner


@map_if_multi_value_filter
def is_curie_format(value: str) -> bool:
    """
    Whether a filter value matches the CURIE (compact URI) format. In our case, for ontology class.
    """
    return bool(P_CURIE.match(value))


@map_if_multi_value_filter
def is_number_query_format(value: str) -> bool:
    """
    Whether a filter value matches any possible number field query.
    Note that this function DOES NOT do any permissions checks for if the query is actually *allowed*.
    """
    return bool(
        P_NUMBER_MAX_VALUE.match(value)
        or P_NUMBER_RANGE.match(value)
        or P_NUMBER_MIN_VALUE.match(value)
        or P_NUMBER_EXACT_VALUE.match(value)
    )


@map_if_multi_value_filter
def is_date_query_format(value: str) -> bool:
    """
    Whether a filter value matches any possible date field query.
    Note that this function DOES NOT do any permissions checks for if the query is actually *allowed*; for example,
    arbitrary ranges shouldn't be allowed with censored discovery.
    """
    return bool(
        P_DATE_BIN.match(value)
        or P_DATE_MAX_VALUE.match(value)
        or P_DATE_RANGE.match(value)
        or P_DATE_MIN_VALUE.match(value)
        or P_DATE_EXACT_VALUE.match(value)
    )


async def get_field_bins(query_set: QuerySet, field: str, bin_size: int):
    # computes a new column "binned" by substracting the modulo by bin size to
    # the value which requires binning (e.g. 28 => 28 - 28 % 10 = 20)
    # cast to integer to avoid numbers such as 60.00 if that was a decimal,
    # and aggregate over this value.
    query_set = query_set.annotate(
        binned=Cast(
            F(field) - Func(F(field), bin_size, function="MOD"),
            IntegerField()
        )
    ).values("binned").annotate(total=Count("binned"))
    stats = {item["binned"]: item["total"] async for item in query_set}
    return stats


async def get_field_options(
    queryset_entity: DiscoveryEntity,
    field_id: str,
    scope: ValidatedDiscoveryScope,
    field_permissions: DataPermissions,
) -> list[str] | list[OntologyClass]:
    """
    Given properties for a discovery field, return the list of authorized options for
    querying this field.
    """

    # Rather than accepting a queryset as a parameter, we use the whole-scope queryset for the entity to calculate field
    # options. We don't want to apply any filtering to the queryset used to determine field options, to avoid filters on
    # the queryset accidentally eliminating valid options.
    queryset = get_discovery_entity_model_scoped_queryset(queryset_entity, scope)

    field_props = scope.discovery.fields[field_id]

    if field_props.datatype in ("string", "ontology-class"):
        options = await get_distinct_field_values(
            queryset_entity, queryset, scope.discovery, field_props, field_permissions
        )
    elif field_props.datatype == "number":
        options = [label for _floor, _ceil, label in f_utils.labelled_number_range_generator(field_props)]
    elif field_props.datatype == "date":
        start, end = await get_month_date_range(
            queryset_entity, queryset, field_props, threshold=get_threshold(scope, field_permissions)
        )
        options = [label for _floor, _ceil, label in f_utils.labelled_date_range_generator_by_month(start, end)]
    else:  # pragma: no cover
        # Can't actually occur with Pydantic implementation of the discovery configuration model, which will validate
        # the data_type value.
        raise NotImplementedError()

    return options


async def get_distinct_field_values(
    queryset_entity: DiscoveryEntity,
    queryset: QuerySet,
    discovery: DiscoveryConfig,
    field_props: FieldDefinition,
    field_permissions: DataPermissions,
) -> list[str] | list[OntologyClass]:
    # get_distinct_field_values can be used by either string or ontology-class fields

    # We must be careful here not to leak 'small cell' values as options
    # - e.g., if there are three individuals with sex=UNKNOWN_SEX, this should be treated as if the field isn't in the
    #   database at all.
    # Thankfully, queryset_stats_for_field handles this for us.

    mapping_field = f_utils.get_field_django_mapping(queryset_entity, field_props)
    field_stats = await queryset_stats_for_field(queryset, mapping_field, field_props, discovery, field_permissions)

    if field_props.datatype == "ontology-class":
        res = [OntologyClass(id=k, label=v[0]) for k, v in field_stats.items()]
        # Ensure options have a consistent sort order. For now, sort alphabetically, but in the future we may wish to
        # sort by count or something like that.
        res.sort(key=lambda t: t.label.casefold())
    else:
        # field_stats keys are already sorted alphabetically
        res = list(field_stats.keys())

    return res


async def compute_binned_ages(individual_queryset: QuerySet, bin_size: int) -> list[int]:
    """
    When age_numeric field is not available, use this function to process
    the age field in its various formats.
    Params:
        - individual_queryset: a queryset made on the individual model, containing
            the age and age_numeric fields
        - bin_size: how many years there is per bin
    Returns a list of values floored to the closest decade (e.g. 25 --> 20)
    """

    a = individual_queryset.filter(age_numeric__isnull=True).values('time_at_last_encounter')
    binned_ages = []
    async for r in a:
        if r["time_at_last_encounter"] is None:
            continue
        age = f_utils.parse_individual_age(r["time_at_last_encounter"])
        binned_ages.append(age - age % bin_size)

    return binned_ages


async def get_age_numeric_binned(
    individual_queryset: QuerySet,
    bin_size: int,
    discovery: DiscoveryConfig,
    field_permissions: DataPermissions,
) -> dict:
    """
    age_numeric is computed at ingestion time of phenopackets. On some instances
    it might be unavailable and as a fallback must be computed from the age JSON field which
    has two alternate formats (hence more complex and slower to process)
    """
    individuals_age = await get_field_bins(individual_queryset, "age_numeric", bin_size)
    if None not in individuals_age:
        return individuals_age

    del individuals_age[None]
    individuals_age = Counter(individuals_age)
    individuals_age.update(
        # single update instead of creating iterables in a loop
        await compute_binned_ages(individual_queryset, bin_size)
    )

    return {
        b: thresholded_count(bv, discovery, field_permissions)
        for b, bv in individuals_age.items()
    }


def _month_start_end_from_stats(stats: dict[str, tuple[str, int]], threshold: int) -> tuple[str | None, str | None]:
    """
    Given ISO date stats of format {YYYY-MM-...: count}, truncates and groups keys based on month and finds the
    starting and ending months which exceed the censorship threshold.
    """

    # Key the counts on yyyy-mm combination (aggregate same month counts)
    grouped_stats = defaultdict(int)
    for sk, sv in stats.items():
        grouped_stats[sk[:LENGTH_Y_M]] += sv[1]

    # filter + sort grouped stats to find start/end dates that exceed censorship threshold
    if items := sorted(filter(lambda item: bool(censor_count(item[1], threshold)), grouped_stats.items())):
        return items[0][0], items[-1][0]

    return None, None


async def get_month_date_range(
    queryset_entity: DiscoveryEntity, queryset: QuerySet, field_props: DateFieldDefinition, threshold: int
) -> tuple[str | None, str | None]:
    """
    Get start date and end date for a field from the database.
    Note that dates within a JSON are stored as strings, not instances of datetime.
    TODO: for now only dates binned by month are handled.
    """

    # As mentioned above, currently only bin_by=month is supported. This is validated by the Pydantic model, so we don't
    # need to check for it here.

    field = f_utils.get_field_django_mapping(queryset_entity, field_props)
    stats = await queryset_stats_for_field(
        queryset, field, field_props, None, None, should_censor=False
    )
    return _month_start_end_from_stats(stats, threshold)


async def get_range_stats(
    scope: ValidatedDiscoveryScope,
    queryset_entity: DiscoveryEntity,
    queryset: QuerySet,
    field_props: NumberFieldDefinition | DateFieldDefinition,
    field_permissions: DataPermissions,
) -> BinList:
    """
    Get binned statistics for a continuous-ish-valued field (number or date). Used for calculating valid options with
    censored discovery or for rendering a histogram.
    """

    field_mapping = f_utils.get_field_django_mapping(queryset_entity, field_props)

    # JSONField array specific field props
    group_by = getattr(field_props, "group_by", None)
    group_by_value = getattr(field_props, "group_by_value", None)
    value_mapping = getattr(field_props, "value_mapping", None)

    if isinstance(field_props, NumberFieldDefinition):
        bin_ranges = tuple(f_utils.labelled_number_range_generator(field_props))
    else:
        threshold = get_threshold(scope, field_permissions)
        start, end = await get_month_date_range(queryset_entity, queryset, field_props, threshold)
        bin_ranges = tuple(f_utils.labelled_date_range_generator_by_month(start, end))

    # Generate a list of When conditions that return a label for the given bin.
    # This is equivalent to an SQL CASE statement.
    if group_by and group_by_value and value_mapping:
        # group_by, group_by_value and value_mapping are required field props to get range stats on a JSONField array.
        whens = [When(
            # Django's gte and lt lookups cannot span multiple JSON array indexes,
            # so we use the jsonb_path_exists function instead.
            f_utils.get_json_range_condition(
                queryset_entity, field_props, min_value=floor, max_value=ceil, max_inclusive=False
            ),
            then=Value(label)
        ) for floor, ceil, label in bin_ranges]
    else:
        whens = [
            When(
                **{f"{field_mapping}__gte": floor} if floor is not None else {},
                **{f"{field_mapping}__lt": ceil} if ceil is not None else {},
                then=Value(label),
            )
            for floor, ceil, label in bin_ranges
        ]

    # use pk__in the search queryset for annotating our bins+counts, otherwise we get weird counts (vs. using the search
    # queryset directly).
    # TODO: cache IDs from search queryset?
    stats_queryset = (
        get_discovery_entity_model_scoped_queryset(queryset_entity, scope).filter(pk__in=queryset)
        .values(label=Case(*whens, default=Value("missing"), output_field=CharField()))
        .annotate(total=Count("label"))
    )

    # Maximum number of entries needed to round a count from its true value down to 0 (censored discovery)
    stats: dict[str, int] = dict()
    async for item in stats_queryset:
        stats[item["label"]] = thresholded_count(item["total"], scope, field_permissions)

    # All the bins between start and end must be represented and ordered
    bins: BinList = BinList(root=[
        BinWithValue(key=label, label=label, value=stats.get(label, 0))
        for floor, ceil, label in bin_ranges
    ])

    if "missing" in stats:
        bins.append(BinWithValue(key="missing", label="missing", value=stats["missing"]))

    return bins


async def get_categorical_stats(
    scope: ValidatedDiscoveryScope,
    queryset_entity: DiscoveryEntity,
    queryset: QuerySet,
    field_props: StringFieldDefinition | OntologyClassFieldDefinition,
    field_permissions: DataPermissions,
) -> BinList:
    """
    Fetches statistics for a given categorical field and apply privacy policies
    """

    # Collect stats for the field, censoring low cell counts along the way
    # - We cannot append 0-counts for derived labels, since that indicates there is a non-0 count for this label in the
    #   database - i.e., if the label is pulled from the values in the database, someone could otherwise learn
    #   1 <= this field <= threshold given it being present at all.
    # - stats_for_field(...) handles this!
    stats: dict[str, tuple[str, int]] = await queryset_stats_for_field(
        # use pk__in the search queryset for annotating our bins+counts, otherwise we get weird counts (vs. using the
        # search queryset directly).
        # TODO: cache IDs from search queryset?
        queryset=get_discovery_entity_model_scoped_queryset(queryset_entity, scope).filter(pk__in=queryset),
        field=f_utils.get_field_django_mapping(queryset_entity, field_props),
        field_props=field_props,
        discovery=scope.discovery,
        field_permissions=field_permissions,
        add_missing=True,
    )

    # Create bin structures for each entry of {key: (label, value)}
    return BinList(root=[BinWithValue(key=k, label=lab, value=v) for k, (lab, v) in stats.items()])


def get_condition_for_non_jsonb_field(
    field: str,
    ops: tuple[tuple[str | None, int | str], ...],
    subquery: DiscoveryFieldSubquery | None,
):
    if subquery:
        # If we do a simple filter on `field` in the case of crossing a many-to-many or many-to-one
        # relationship boundary, we end up with an inner join that prevents us from getting correct stats of
        # values for the matching queryset entity.
        # Instead, we do an Exists subquery to check if we have at least one matching object from the other side
        # of the m2m/many-to-one relation which matches the field query (which as been rewritten to be valid for
        # the model referred to in the relation rather than the queryset model.)
        return Q(Exists(
            subquery.queryset.filter(**{
                subquery.related_field: OuterRef("pk"),
                **{f"{subquery.inner_field}{'__' + op if op is not None else ''}": value for op, value in ops}
            })
        ))
    else:
        return Q(**{f"{field}{'__' + op if op is not None else ''}": value for op, value in ops})


def symbol_django_op(sym: str) -> str:
    match sym:
        case "<" | ")":
            return "lt"
        case "≤" | "]":
            return "lte"
        case ">" | "(":
            return "gt"
        case "≥" | "[":
            return "gte"
        case _:  # pragma: no cover
            # Shouldn't occur, as the regex check should prevent these queries from being made
            raise NotImplementedError()


def _cast_field_value(field_props: FieldDefinition, value: str) -> str | int | float:
    """Given a field and a string value, cast the value to the field type if needed (right now, just numbers)."""
    return f_utils.str_to_numeric(value) if field_props.datatype == "number" else value


def filter_range_condition(
    queryset_entity: DiscoveryEntity,
    field_props: FieldDefinition,
    match: re.Match,
    field: str,
    subquery: DiscoveryFieldSubquery | None,
) -> Q:
    # full value looks like "[50, 60)", "< 50", or "≥ 60" if we're validating bins line up with censored
    # discovery (validated elsewhere).
    # with full discovery access (query:data), we can accept the following other forms:
    #   "(50, 60)", "[50, 60)", "[50, 60]", "≥50, <60", "≤ 50", "> 60"
    # with full discovery access, we can also accept date ranges.

    start_op = symbol_django_op(match["start_sym"])
    end_op = symbol_django_op(match["end_sym"])
    start = _cast_field_value(field_props, match["start"])
    end = _cast_field_value(field_props, match["end"])

    if json_range_condition := f_utils.get_json_range_condition(
        queryset_entity,
        field_props,
        min_value=start,
        min_inclusive=start_op == "gte",
        max_value=end,
        max_inclusive=end_op == "lte",
    ):
        # JSONField array range stats must use 'jsonb_path_exists' conditions
        return json_range_condition
    else:
        return get_condition_for_non_jsonb_field(field, ((start_op, start), (end_op, end)), subquery)


def filter_minimum_condition(
    queryset_entity: DiscoveryEntity,
    field_props: FieldDefinition,
    match: re.Match,
    field: str,
    subquery: DiscoveryFieldSubquery | None,
) -> Q:
    # full value looks like "> 50" or "≥ 50", where 50 is the minimum value either exclusively or inclusively.
    # only the latter is valid for censored discovery.
    val = _cast_field_value(field_props, match["val"])
    op = symbol_django_op(match["sym"])
    if json_range_condition := f_utils.get_json_range_condition(
        queryset_entity, field_props, min_value=val, min_inclusive=op == "gte"
    ):
        return json_range_condition
    else:
        return get_condition_for_non_jsonb_field(field, ((op, val),), subquery)


def filter_maximum_condition(
    queryset_entity: DiscoveryEntity,
    field_props: FieldDefinition,
    match: re.Match,
    field: str,
    subquery: DiscoveryFieldSubquery | None,
) -> Q:
    # full value looks like "< 50" or "≤ 50", where 50 is the maximum either exclusively or inclusively.
    # only the former is valid for censored discovery.
    val = _cast_field_value(field_props, match["val"])
    op = symbol_django_op(match["sym"])
    if json_range_condition := f_utils.get_json_range_condition(
        queryset_entity, field_props, max_value=val, max_inclusive=op == "lte"
    ):
        return json_range_condition
    else:
        return get_condition_for_non_jsonb_field(field, ((op, val),), subquery)


def filter_equality_condition(
    queryset_entity: DiscoveryEntity,
    field_props: FieldDefinition,
    match: re.Match,
    field: str,
    subquery: DiscoveryFieldSubquery | None,
) -> Q:
    # basic equality condition using provided value
    val = _cast_field_value(field_props, match["val"])
    if json_range_condition := f_utils.get_json_op_condition(queryset_entity, field_props, f_utils.OP_EQ, val):
        return json_range_condition
    else:
        return get_condition_for_non_jsonb_field(field, ((None, val),), subquery)


def queryset_field_single_value_condition(
    queryset_entity: DiscoveryEntity,
    field: str,
    field_props: FieldDefinition,
    value: str,
    subquery: DiscoveryFieldSubquery | None,
):
    if field_props.datatype in ("string", "ontology-class"):
        is_ontology_class = field_props.datatype == "ontology-class"
        if gb := field_props.group_by:
            # JSONField array string check must use 'contains' lookup
            nested_condition = f_utils.get_nested_json_condition(gb + ("/id" if is_ontology_class else ""), value)
            condition = Q(**{f"{field}__contains": [nested_condition]})
            # TODO: not properly defined for ontology-class fields
        else:
            condition = get_condition_for_non_jsonb_field(field, (("iexact", value),), subquery)

    elif field_props.datatype == "number":
        # values are of the form "[50, 150)", "< 50" or "≥ 800".
        # important: custom bins can have decimals in them!

        if mrp_match := P_NUMBER_RANGE.match(value):
            # full value looks like "[50, 60)", "< 50", or "≥ 60" if we're validating bins line up with censored
            # discovery (validated elsewhere).
            # with full discovery access (query:data), we can accept the following other forms:
            #   "(50, 60)", "[50, 60)", "[50, 60]", "≥50, <60", "≤ 50", "> 60"
            condition = filter_range_condition(queryset_entity, field_props, mrp_match, field, subquery)

        elif min_match := P_NUMBER_MIN_VALUE.match(value):
            # full value looks like "> 50" or "≥ 50", where 50 is the minimum value either exclusively or inclusively.
            # only the latter is valid for censored discovery.
            condition = filter_minimum_condition(queryset_entity, field_props, min_match, field, subquery)

        elif max_match := P_NUMBER_MAX_VALUE.match(value):
            # full value looks like "< 50" or "≤ 50", where 50 is the maximum either exclusively or inclusively.
            # only the former is valid for censored discovery.
            condition = filter_maximum_condition(queryset_entity, field_props, max_match, field, subquery)

        elif exact_match := P_NUMBER_EXACT_VALUE.match(value):
            # full value looks like a number ("50.0", "50", "-5"). not valid for censored discovery.
            condition = filter_equality_condition(queryset_entity, field_props, exact_match, field, subquery)

        else:
            raise NotImplementedError(f"Could not handle number value: '{value}'")

    elif field_props.datatype == "date":
        if P_DATE_BIN.match(value):
            # Date bin expressed as "yyyy-mm", as available in censored discovery
            condition = get_condition_for_non_jsonb_field(field, (("startswith", value),), subquery)

        elif mrp_match := P_DATE_RANGE.match(value):
            # full value looks like [2022, 2023) or [2022, 2024] or [2022-02, 2023-01) or ...
            condition = filter_range_condition(queryset_entity, field_props, mrp_match, field, subquery)

        elif min_match := P_DATE_MIN_VALUE.match(value):
            # full value looks like "≥ 2022-01" or "> 2023" (uses lexicographic ordering)
            condition = filter_minimum_condition(queryset_entity, field_props, min_match, field, subquery)

        elif max_match := P_DATE_MAX_VALUE.match(value):
            # full value looks like "≤ 2022-01" or "< 2023" (uses lexicographic ordering)
            condition = filter_maximum_condition(queryset_entity, field_props, max_match, field, subquery)

        elif date_match := P_DATE_EXACT_VALUE.match(value):
            # full value looks like "2022-01-03" (ISO date format)
            condition = filter_equality_condition(queryset_entity, field_props, date_match, field, subquery)

        else:
            raise NotImplementedError(f"Could not handle date value: '{value}'")

    else:  # pragma: no cover
        # This isn't possible to reach by normal means, since the FieldDefinition Pydantic model limits the possible
        # values of `datatype` to the cases above (unless a new possible value is added to FieldDefinition).
        raise NotImplementedError()

    return condition


async def filter_queryset_field_value(
    queryset_entity: DiscoveryEntity,
    qs: QuerySet,
    field_props: FieldDefinition,
    value: str | DiscoveryQueryFilterOneOf,
    logger: BoundLogger
) -> tuple[QuerySet, DiscoveryEntity]:
    """
    Further filter a queryset using the field defined by field_props and the
    given value.
    It is a prerequisite that the field mapping defined in field_props is represented
    in the queryset object.
    `mapping_for_search_filter` is an optional property that gets precedence over `mapping`
    for the necessity of filtering. It is not necessary to specify this when
    the `mapping` value is based on the same model as the queryset.
    """

    # - can throw DiscoveryFilterRewriteException if we cannot rewrite the field mapping as a subpath of the queryset
    #   model
    field, subq, queried_entity = get_field_django_mapping_and_queried_entity(
        queryset_entity, field_props, resolve_ontology_class=True
    )

    # TODO: resolve schema including extra properties

    if isinstance(value, DiscoveryQueryFilterOneOf):
        # build the OR query if our filter value is DiscoveryQueryFilterOneOf
        condition = queryset_field_single_value_condition(queryset_entity, field, field_props, value.values[0], subq)
        for v in value.values[1:]:
            condition |= queryset_field_single_value_condition(queryset_entity, field, field_props, v, subq)
        if value.negated:
            condition = ~condition
    else:
        condition = queryset_field_single_value_condition(queryset_entity, field, field_props, value, subq)

    await logger.adebug(
        "filtering entity field with condition", entity=queried_entity, field=field, condition=condition
    )

    return qs.filter(condition), queried_entity
