# Generated by Django 2.2.6 on 2019-10-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='The id of the Individual this biosample was derived from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biosamples', to='patients.Individual'),
        ),
    ]
