# Generated by Django 2.2.7 on 2019-12-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='alternate_id',
            new_name='alternate_ids',
        ),
    ]
