# Generated by Django 2.2.9 on 2020-01-21 19:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0002_auto_20200121_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='histological_diagnosis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term representing a refinement of the clinical diagnosis. Normal samples could be tagged with NCIT:C38757, representing a negative finding.', null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='sampled_tissue',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology term describing the tissue from which the specimen was collected. The use of UBERON is recommended.'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='taxonomy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term specified when more than one organism may be studied. It is advised that codesfrom the NCBI Taxonomy resource are used, e.g. NCBITaxon:9606 for humans.', null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_grade',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term representing the tumour grade. This should be a child term of NCIT:C28076 (Disease Grade Qualifier) or equivalent.', null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_progression',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term representing if the specimen is from a primary tumour, a metastasis, or a recurrence. There are multiple ways of representing this using ontology terms, and the terms chosen will have a specific meaning that is application specific..', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='term',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="An ontology term that represents the disease. It's recommended that one of the OMIM, Orphanet, or MONDO ontologies is used for rare human diseases."),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='onset',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term that describes the age at which the phenotypic feature was first noticed or diagnosed, e.g. HP:0003674.', null=True),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='pftype',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology term which describes the phenotype.', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='severity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term that describes the severity of the condition.', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='body_site',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term that is specified when it is not possible to represent the procedure with a single ontology class.', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology term that represents a clinical procedure performed on a subject.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='zygosity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology term taken from the Genotype Ontology (GENO) representing the zygosity of the variant.', null=True),
        ),
    ]
