# Generated by Django 2.2.6 on 2019-10-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0002_auto_20191030_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='phenopacket',
            field=models.ForeignKey(help_text='The subject of this interpretation.', on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='phenopackets.Phenopacket'),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='subject',
            field=models.ForeignKey(help_text='The proband.', on_delete=django.db.models.deletion.CASCADE, related_name='phenopackets', to='patients.Individual'),
        ),
    ]
