# Generated by Django 2.2.7 on 2019-12-04 22:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0002_auto_20191204_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='age_of_onset',
            new_name='onset',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='tumor_stage',
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_stage',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='List of terms representing the disease stage.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='disease',
            name='tnm_finding',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='List of terms representing the tumor TNM score.', null=True, size=None),
        ),
    ]
