# Generated by Django 4.1.3 on 2023-01-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0003_v2_14_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='biosample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenotypic_features', to='phenopackets.biosample'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='phenopacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenotypic_features', to='phenopackets.phenopacket'),
        ),
    ]
