# Generated by Django 2.2.6 on 2019-11-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0003_auto_20191030_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='phenotypic_features',
        ),
        migrations.RemoveField(
            model_name='phenopacket',
            name='phenotypic_features',
        ),
        migrations.AddField(
            model_name='phenotypicfeature',
            name='biosample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotypic_features', to='phenopackets.Biosample'),
        ),
        migrations.AddField(
            model_name='phenotypicfeature',
            name='phenopacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenotypic_features', to='phenopackets.Phenopacket'),
        ),
    ]
