# Generated by Django 2.2.6 on 2019-11-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0004_auto_20191101_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phenotypicfeature',
            old_name='_type',
            new_name='pftype',
        ),
    ]
