# Generated by Django 2.2.6 on 2019-11-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0005_auto_20191104_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableownership',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='tableownership',
            name='sample',
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chord.Dataset'),
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TableOwnership',
        ),
    ]
