# Generated by Django 4.2.1 on 2023-06-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0006_phenopacket_unique_pheno_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenopacket',
            name='table',
        ),
    ]
