# Generated by Django 4.2.7 on 2024-01-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0008_v6_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='diagnosis',
            field=models.OneToOneField(blank=True, help_text='One or more diagnoses, if made.', null=True, on_delete=django.db.models.deletion.CASCADE, to='phenopackets.diagnosis'),
        ),
    ]
