# Generated by Django 2.2.12 on 2020-05-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0008_auto_20200514_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='diagnostic_markers',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='disease_stage',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='tnm_finding',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='external_references',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='updates',
        ),
        migrations.RemoveField(
            model_name='phenotypicfeature',
            name='modifier',
        ),
    ]
