# Generated by Django 2.2.6 on 2019-11-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0008_auto_20191122_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpretation',
            old_name='interpretation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_id',
            new_name='id',
        ),
    ]
