# Generated by Django 2.2.6 on 2019-11-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0010_remove_metadata_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='resources',
            field=models.ManyToManyField(help_text='This element contains a listing of the ontologies/resources referenced in the phenopacket.', to='phenopackets.Resource'),
        ),
    ]
