# Generated by Django 2.2.12 on 2020-05-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0011_auto_20200519_1538'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='resources',
        ),
        migrations.AddField(
            model_name='metadata',
            name='resources',
            field=models.ManyToManyField(help_text='A list of resources or ontologies referenced in the phenopacket', to='resources.Resource'),
        ),
    ]
