# Generated by Django 5.0.11 on 2025-03-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_v11_0_0'),
        ('phenopackets', '0011_v10_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='location_collected',
            field=models.ForeignKey(blank=True, help_text='A GeoJSON-compatible object representing a geographic location.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.geolocation'),
        ),
    ]
