# Generated by Django 5.1.13 on 2025-10-15 15:22

import chord_metadata_service.restapi.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('phenopackets', '0012_v11_0_0'), ('phenopackets', '0013_alter_biosample_diagnostic_markers_and_more'), ('phenopackets', '0014_alter_phenopacket_biosamples_and_more')]

    dependencies = [
        ('geo', '0001_v11_0_0'),
        ('phenopackets', '0011_v10_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='location_collected',
            field=models.ForeignKey(blank=True, help_text='A GeoJSON-compatible object representing a geographic location.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.geolocation'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='diagnostic_markers',
            field=models.JSONField(blank=True, help_text='A list of ontology terms representing clinically-relevant bio-markers.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS_LIST')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='histological_diagnosis',
            field=models.JSONField(blank=True, help_text='An ontology term representing a refinement of the clinical diagnosis. Normal samples could be tagged with NCIT:C38757, representing a negative finding.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='measurements',
            field=models.JSONField(blank=True, help_text='List of measurements of the sample', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='PHENOPACKET_MEASUREMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='pathological_stage',
            field=models.JSONField(blank=True, help_text='An ontology term Pathological stage, if applicable..', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='pathological_tnm_finding',
            field=models.JSONField(blank=True, help_text='Pathological TNM findings, if applicable.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS_LIST')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='sample_type',
            field=models.JSONField(blank=True, help_text='type of material, e.g., RNA, DNA, Cultured cells', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='sampled_tissue',
            field=models.JSONField(blank=True, help_text='An ontology term describing the tissue from which the specimen was collected. The use of UBERON is recommended.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='taxonomy',
            field=models.JSONField(blank=True, help_text='An ontology term specified when more than one organism may be studied. It is advised that codesfrom the NCBI Taxonomy resource are used, e.g. NCBITaxon:9606 for humans.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='time_of_collection',
            field=models.JSONField(blank=True, help_text='Age of the proband at the time the sample was taken.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_grade',
            field=models.JSONField(blank=True, help_text='An ontology term representing the tumour grade. This should be a child term of NCIT:C28076 (Disease Grade Qualifier) or equivalent.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_progression',
            field=models.JSONField(blank=True, help_text='An ontology term representing if the specimen is from a primary tumour, a metastasis, or a recurrence. There are multiple ways of representing this using ontology terms, and the terms chosen will have a specific meaning that is application specific.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='clinical_tnm_finding',
            field=models.JSONField(blank=True, help_text='A list of terms representing the tumour TNM score. Elements should be derived from child terms of NCIT:C48232 (Cancer TNM Finding) or equivalent hierarchy from another ontology.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS_LIST')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_stage',
            field=models.JSONField(blank=True, help_text='A list of terms representing the disease stage. Elements should be derived from child terms of NCIT:C28108 (Disease Stage Qualifier) or equivalent hierarchy from another ontology.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS_LIST')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='laterality',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='onset',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='primary_site',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='resolution',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='disease',
            name='term',
            field=models.JSONField(help_text="An ontology term that represents the disease. It's recommended that one of the OMIM, Orphanet, or MONDO ontologies is used for rare human diseases.", validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='external_references',
            field=models.JSONField(blank=True, help_text='A list of external (non-resource) references.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='VALIDATION_PHENOPACKET_EXTERNAL_REFERENCE_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updates',
            field=models.JSONField(blank=True, help_text='A list of updates to the phenopacket.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=['date-time'], schema_ref='VALIDATION_PHENOPACKET_UPDATE_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='measurements',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='PHENOPACKET_MEASUREMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='medical_actions',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='PHENOPACKET_MEDICAL_ACTION_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='evidence',
            field=models.JSONField(blank=True, help_text='One or more pieces of evidence that specify how the phenotype was determined.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='PHENOPACKET_EVIDENCE_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='modifiers',
            field=models.JSONField(blank=True, help_text='A list of ontology terms that provide more expressive / precise descriptions of a phenotypic feature, including e.g. positionality or external factors.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS_LIST')]),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='onset',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='pftype',
            field=models.JSONField(help_text='An ontology term which describes the phenotype.', validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')], verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='resolution',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='severity',
            field=models.JSONField(blank=True, help_text='An ontology term that describes the severity of the condition.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='allelic_state',
            field=models.JSONField(blank=True, help_text='The zygosity of the variant as determined in all of the samples representedin this Phenopacket is represented using a list of terms taken from the Genotype Ontology (GENO).', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='expressions',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='EXPRESSION_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='extensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='EXTENSION_SCHEMA')]), blank=True, default=list, help_text='List of resource-specific Extensions needed to describe the variation', size=None),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='structural_type',
            field=models.JSONField(blank=True, help_text='The structural variant type associated with this variant, such as a substitution, deletion, or fusion.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='variation',
            field=models.JSONField(blank=True, help_text='The VRS Variation object', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='VRS_VARIATION_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='vcf_record',
            field=models.JSONField(blank=True, null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='VCF_RECORD_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='biosamples',
            field=models.ManyToManyField(blank=True, help_text='Samples (e.g. biopsies) taken from the individual, if any.', related_name='phenopackets', to='phenopackets.biosample'),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='A list of diseases diagnosed in the proband.', related_name='phenopackets', to='phenopackets.disease'),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='interpretations',
            field=models.ManyToManyField(blank=True, help_text='Interpretations related to this phenopacket', related_name='phenopackets', to='phenopackets.interpretation'),
        ),
    ]
