# Generated by Django 5.1.11 on 2025-07-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0012_alter_biosample_diagnostic_markers_and_more'),
        ('phenopackets', '0012_v11_0_0'),
    ]

    operations = [
    ]
