# Generated by Django 2.2.6 on 2019-11-22 21:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0012_auto_20191122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='individual_age_at_collection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Age of the proband at the time the sample was taken.', null=True),
        ),
    ]
