# Generated by Django 5.1.11 on 2025-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0013_alter_biosample_diagnostic_markers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenopacket',
            name='biosamples',
            field=models.ManyToManyField(blank=True, help_text='Samples (e.g. biopsies) taken from the individual, if any.', related_name='phenopackets', to='phenopackets.biosample'),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='A list of diseases diagnosed in the proband.', related_name='phenopackets', to='phenopackets.disease'),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='interpretations',
            field=models.ManyToManyField(blank=True, help_text='Interpretations related to this phenopacket', related_name='phenopackets', to='phenopackets.interpretation'),
        ),
    ]
