# Generated by Django 5.1.11 on 2025-08-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0013_alter_biosample_diagnostic_markers_and_more'),
        ('phenopackets', '0013_merge_0012'),
    ]

    operations = [
    ]
