# Generated by Django 2.2.7 on 2019-11-28 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0013_auto_20191122_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when this object was created.'),
        ),
    ]
