# Generated by Django 5.1.12 on 2025-10-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_individual_gender_alter_individual_taxonomy_and_more'),
        ('phenopackets', '0014_alter_phenopacket_biosamples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenopacket',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='A subject of a phenopacket, representing either a human (typically) or another organism.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenopackets', to='patients.individual'),
        ),
    ]
