# Generated by Django 5.1.11 on 2025-07-31 19:50

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0014_alter_biosample_diagnostic_markers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='external_references',
            field=models.JSONField(blank=True, help_text='A list of external (non-resource) references.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='VALIDATION_PHENOPACKET_EXTERNAL_REFERENCE_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updates',
            field=models.JSONField(blank=True, help_text='A list of updates to the phenopacket.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=['date-time'], schema_ref='VALIDATION_PHENOPACKET_UPDATE_SCHEMA')]),
        ),
    ]
