# Generated by Django 5.1.13 on 2025-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0015_alter_phenopacket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='fts_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phenopacket',
            name='fts_extra',
            field=models.TextField(blank=True, default=''),
        ),
    ]
