# Generated by Django 5.1.13 on 2025-11-14 16:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0010_v11_0_0'),
        ('geo', '0001_v11_0_0_v2'),
        ('patients', '0011_individual_individual_fts_gin_idx'),
        ('phenopackets', '0015_alter_phenopacket_subject'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='biosample',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('id', 'description', django.db.models.functions.comparison.Cast('sampled_tissue', models.TextField()), django.db.models.functions.comparison.Cast('taxonomy', models.TextField()), django.db.models.functions.comparison.Cast('time_of_collection', models.TextField()), django.db.models.functions.comparison.Cast('histological_diagnosis', models.TextField()), django.db.models.functions.comparison.Cast('tumor_progression', models.TextField()), django.db.models.functions.comparison.Cast('tumor_grade', models.TextField()), django.db.models.functions.comparison.Cast('diagnostic_markers', models.TextField()), django.db.models.functions.comparison.Cast('extra_properties', models.TextField()), django.db.models.functions.comparison.Cast('procedure__code', models.TextField()), django.db.models.functions.comparison.Cast('procedure__body_site', models.TextField()), django.db.models.functions.comparison.Cast('procedure__extra_properties', models.TextField())), name='biosample_fts_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='phenopacket',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('id', 'subject__id', 'subject__alternate_ids', 'subject__date_of_birth', 'subject__sex', 'subject__karyotypic_sex', django.db.models.functions.comparison.Cast('subject__gender', models.TextField()), django.db.models.functions.comparison.Cast('subject__taxonomy', models.TextField()), django.db.models.functions.comparison.Cast('subject__time_at_last_encounter', models.TextField()), django.db.models.functions.comparison.Cast('subject__time_at_last_encounter__age', models.TextField()), django.db.models.functions.comparison.Cast('subject__time_at_last_encounter__age_range', models.TextField()), django.db.models.functions.comparison.Cast('subject__vital_status__status', models.TextField()), django.db.models.functions.comparison.Cast('subject__vital_status__time_of_death', models.TextField()), django.db.models.functions.comparison.Cast('subject__vital_status__cause_of_death', models.TextField()), django.db.models.functions.comparison.Cast('subject__vital_status__survival_time_in_days', models.TextField()), django.db.models.functions.comparison.Cast('subject__extra_properties', models.TextField())), name='phenopacket_fts_gin_idx'),
        ),
    ]
