# Generated by Django 5.2.10 on 2026-01-16 20:11

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0016_biosample_fts_extra_phenopacket_fts_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.JSONField(validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
    ]
