# Generated by Django 5.2.11 on 2026-02-25 18:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_v13_1_0'),
        ('geo', '0001_v11_0_0_v2'),
        ('patients', '0012_v13_1_0'),
        ('phenopackets', '0016_biosample_fts_extra_phenopacket_fts_extra'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='biosample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='sample_id_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='biosample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='sample_description_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='biosample',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts_extra'], name='sample_fts_extra_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phenopacket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='pheno_id_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phenopacket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts_extra'], name='pheno_fts_extra_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
