# Generated by Django 5.2.12 on 2026-03-30 21:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_v13_1_0'),
        ('patients', '0013_v13_2_0'),
        ('phenopackets', '0017_v13_1_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disease',
            index=django.contrib.postgres.indexes.GinIndex(fields=['term'], name='disease_term_idx'),
        ),
        migrations.AddIndex(
            model_name='phenopacket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['measurements'], name='pheno_measurements_idx'),
        ),
        migrations.AddIndex(
            model_name='phenopacket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['medical_actions'], name='pheno_medical_actions_idx'),
        ),
    ]
