# Generated by Django 6.1 on 2026-09-01 12:39

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0019_phenopacket_dataset_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='taxonomy',
            field=models.JSONField(blank=True, help_text='An ontology term specified when more than one organism may be studied. It is advised that codes from the NCBI Taxonomy resource are used, e.g. NCBITaxon:9606 for humans.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='variationdescriptor',
            name='allelic_state',
            field=models.JSONField(blank=True, help_text='The zygosity of the variant as determined in all of the samples represented in this Phenopacket is represented using a list of terms taken from the Genotype Ontology (GENO).', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
    ]
