"""
Make ER diagram

Date: 2024-01-02
Author: Marion Shadbolt

Script to generate an ER diagram using mermaid syntax of the katsu moh model defined in
katsu/chord_metadata_service/mohpackets/models.py.

The script uses automated parsing of class definitions in the models.py file by pyreverse. It then does some string
replacement to clean up the output and transform into a mermaid ER diagram. Finally, relationships between each class
are manually defined. If relationships change in the future, these should be updated.

Prerequisites:
* A mermaid class diagram (classes.mmd) in this directory generated by pyreverse.
    * to generate this, install pylint and run 'pyreverse -o mmd ../models.py'

To run:
python make_er_diagram.py

Output:
* a file to the current directory called 'er_diagram.md'.

"""

from datetime import datetime
import os
import re


def main():
    mmd_file = f"{os.path.dirname(os.path.realpath(__file__))}/classes.mmd"
    with open(mmd_file, "r") as classes_file:
        class_diagram = classes_file.read()
        # Remove unwanted text and transform to erDiagram
        er_diagram = re.sub(r'class Meta {\n\s+ordering : list\n\s+}\n\s+', '', class_diagram)
        er_diagram = re.sub(r'class Meta {\n\s+ordering : list\n\s+unique_together : list\n\s+}\n\s+', '', er_diagram)
        # er_diagram = er_diagram.replace("    ordering list\n  }\n", "")
        # ordering list\n  }\n", "")
        er_diagram = er_diagram.replace("class AutoDateTimeFi ordering list\n}\n", "")
        er_diagram = er_diagram.replace("class AutoDateTimeField {\n    pre_save(model_instance, add)\n  }\n", "")
        er_diagram = er_diagram.replace(": ", "")
        er_diagram = er_diagram.replace("AutoDateTimeField --* Program updated", "")
        er_diagram = er_diagram.replace("updated", "updated AutoDateTimeField")

    with open("er_diagram.md", "w+") as er_file:
        # Intro text
        er_file.write("*This file is automatically generated, do not edit directly.*\n\n"
                      f"This file was last generated on {datetime.today().strftime('%Y-%m-%d %H:%M:%S')}. See README "
                      f"for how to regenerate.\n\n"
                      "You can view the below diagram in a nicer viewer by hitting the 'copy' button and pasting it "
                      "into the live editor on [mermaid.live](https://mermaid.live)\n\n")
        # Mermaid diagram block
        er_file.write("```mermaid\n")
        er_file.write(er_diagram)
        # Define linking relationships
        er_file.write('Program -- Donor : ""\n'
                      'Program -- PrimaryDiagnosis : ""\n'
                      'Program -- Comorbidity : ""\n'
                      'Program -- Biomarker : ""\n'
                      'Program -- Exposure : ""\n'
                      'Program -- FollowUp : ""\n'
                      'Program -- Specimen : ""\n'
                      'Program -- Treatment : ""\n'
                      'Program -- SampleRegistration : ""\n'
                      'Program -- SystemicTherapy : ""\n'
                      'Program -- Radiation : ""\n'
                      'Program -- Surgery : ""\n'
                      'Donor -- PrimaryDiagnosis : ""\n'
                      'Donor -- Comorbidity : ""\n'
                      'Donor -- Biomarker\n'
                      'Donor -- Exposure\n'
                      'Donor -- FollowUp\n'
                      'Donor -- Specimen\n'
                      'Donor -- Treatment\n'
                      'Donor -- SampleRegistration\n'
                      'Donor -- SystemicTherapy\n'
                      'Donor -- Radiation\n'
                      'Donor -- Surgery\n'
                      'PrimaryDiagnosis -- Specimen\n'
                      'PrimaryDiagnosis -- Treatment\n'
                      'PrimaryDiagnosis -- FollowUp\n'
                      'Specimen -- SampleRegistration\n'
                      'Treatment -- SystemicTherapy\n'
                      'Treatment -- Radiation\n'
                      'Treatment -- Surgery\n'
                      'Treatment -- FollowUp\n'
                      '\n```\n')


if __name__ == '__main__':
    main()
