"""
Make ER diagram

Date: 2023-10-19
Author: Marion Shadbolt

Script to generate an ER diagram using mermaid syntax of the katsu moh model defined in
katsu/chord_metadata_service/mohpackets/models.py.

The script uses automated parsing of class definitions in the models.py file by pyreverse. It then does some string
replacement to clean up the output and transform into a mermaid ER diagram. Finally, relationships betweem each class
are manually defined. If relationships change in the future, these should be updated.

Prerequisites:
* A mermaid class diagram (classes.mmd) in this directory generated by pyreverse.
    * to generate this, install pylint and run 'pyreverse -o mmd ../models.py'

To run:
python make_er_diagram.py

Output:
* a file to the current directory called 'er_diagram.md'.

"""

from datetime import datetime


def main():

    with open("classes.mmd", "r") as classes_file:
        class_diagram = classes_file.read()
        # Remove unwanted text and transform to erDiagram
        er_diagram = class_diagram.replace("class ", "")
        er_diagram = er_diagram.replace("classDiagram", "erDiagram")
        er_diagram = er_diagram.replace("  Meta {\n    ordering : list\n  }\n", "")
        er_diagram = er_diagram.replace("  AutoDateTimeField {\n    pre_save(model_instance, add)\n  }\n", "")
        er_diagram = er_diagram.replace(": ", "")
        er_diagram = er_diagram.replace("AutoDateTimeField --* Program updated", "")
        er_diagram = er_diagram.replace("updated", "updated AutoDateTimeField")

    with open("er_diagram.md", "w+") as er_file:
        # Intro text
        er_file.write("*This file is automatically generated, do not edit directly.*\n\n"
                      f"This file was last generated on {datetime.today().strftime('%Y-%m-%d %H:%M:%S')}. See README "
                      f"for how to regenerate.\n\n"
                      "You can view the below diagram in a nicer viewer by hitting the 'copy' button and pasting it "
                      "into the live editor on [mermaid.live](https://mermaid.live)\n\n")
        # Mermaid diagram block
        er_file.write("```mermaid\n")
        er_file.write(er_diagram)
        # Define linking relationships
        er_file.write('Program ||--o{ Donor : ""\n'
                      'Program ||--o{ PrimaryDiagnosis : ""\n'
                      'Program ||--o{ Comorbidity : ""\n'
                      'Program ||--o{ Biomarker : ""\n'
                      'Program ||--o{ Exposure : ""\n'
                      'Program ||--o{ FollowUp : ""\n'
                      'Program ||--o{ Specimen : ""\n'
                      'Program ||--o{ Treatment : ""\n'
                      'Program ||--o{ SampleRegistration : ""\n'
                      'Program ||--o{ Chemotherapy : ""\n'
                      'Program ||--o{ HormoneTherapy : ""\n'
                      'Program ||--o{ Immunotherapy : ""\n'
                      'Program ||--o{ Radiation : ""\n'
                      'Program ||--o{ Surgery : ""\n'
                      'Donor ||--o{ PrimaryDiagnosis : ""\n'
                      'Donor ||--o{ Comorbidity : ""\n'
                      'Donor ||--o{ Biomarker : "" \n'
                      'Donor ||--o{ Exposure : "" \n'
                      'Donor ||--o{ FollowUp : "" \n'
                      'Donor ||--o{ Specimen : "" \n'
                      'Donor ||--o{ Treatment : "" \n'
                      'Donor ||--o{ SampleRegistration : "" \n'
                      'Donor ||--o{ Chemotherapy : "" \n'
                      'Donor ||--o{ HormoneTherapy : "" \n'
                      'Donor ||--o{ Immunotherapy : "" \n'
                      'Donor ||--o{ Radiation : "" \n'
                      'Donor ||--o{ Surgery : "" \n'
                      'PrimaryDiagnosis ||--o{ Specimen : "" \n'
                      'PrimaryDiagnosis ||--o{ Treatment : "" \n'
                      'PrimaryDiagnosis ||--o{ FollowUp : "" \n'
                      'Specimen ||--o{ SampleRegistration : "" \n'
                      'Treatment ||--o{ Chemotherapy : "" \n'
                      'Treatment ||--o{ HormoneTherapy : "" \n'
                      'Treatment ||--o{ Immunotherapy : "" \n'
                      'Treatment ||--o{ Radiation : "" \n'
                      'Treatment ||--o{ Surgery : "" \n'
                      'Treatment ||--o{ FollowUp : "" \n'
                      '\n```\n')


if __name__ == '__main__':
    main()
