from enum import Enum
from chord_metadata_service.discovery.schemas import DISCOVERY_SCHEMA
from chord_metadata_service.experiments.schemas import EXPERIMENT_RESULT_FILE_INDEX_LIST_SCHEMA
from chord_metadata_service.phenopackets.schemas import *
from chord_metadata_service.restapi.schemas import *

__all__ = [
    "SchemaRefs",
]

class SchemaRefs(Enum):
    ONTOLOGY_CLASS = ONTOLOGY_CLASS
    ONTOLOGY_CLASS_LIST = ONTOLOGY_CLASS_LIST
    KEY_VALUE_OBJECT = KEY_VALUE_OBJECT
    AGE_STRING = AGE_STRING
    AGE = AGE
    AGE_RANGE = AGE_RANGE
    AGE_OR_AGE_RANGE = AGE_OR_AGE_RANGE
    TIME_INTERVAL = TIME_INTERVAL
    EXTRA_PROPERTIES_SCHEMA = EXTRA_PROPERTIES_SCHEMA
    GESTATIONAL_AGE = GESTATIONAL_AGE
    TIME_ELEMENT_SCHEMA = TIME_ELEMENT_SCHEMA
    DISCOVERY_SCHEMA = DISCOVERY_SCHEMA
    EXPERIMENT_RESULT_FILE_INDEX_LIST_SCHEMA = EXPERIMENT_RESULT_FILE_INDEX_LIST_SCHEMA
    PHENOPACKET_EVIDENCE_SCHEMA = PHENOPACKET_EVIDENCE_SCHEMA
    PHENOPACKET_MEASUREMENT_SCHEMA = PHENOPACKET_MEASUREMENT_SCHEMA
    EXPRESSION_SCHEMA = EXPRESSION_SCHEMA
    VCF_RECORD_SCHEMA = VCF_RECORD_SCHEMA
    EXTENSION_SCHEMA = EXTENSION_SCHEMA
    PHENOPACKET_MEDICAL_ACTION_SCHEMA = PHENOPACKET_MEDICAL_ACTION_SCHEMA
    VRS_VARIATION_SCHEMA = VRS_VARIATION_SCHEMA
    VALIDATION_PHENOPACKET_UPDATE_SCHEMA = VALIDATION_PHENOPACKET_UPDATE_SCHEMA
    VALIDATION_PHENOPACKET_EXTERNAL_REFERENCE_SCHEMA = VALIDATION_PHENOPACKET_EXTERNAL_REFERENCE_SCHEMA
