# Generated by Django 5.2.11 on 2026-03-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0012_rename_pcgl_to_study'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetv2',
            name='chord_datas_id_327358_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetv2',
            name='chord_datas_release_8ef27a_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetv2',
            name='chord_datas_last_mo_2b6d24_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetv2',
            name='chord_datas_study_s_675827_idx',
        ),
        migrations.AddField(
            model_name='datasetv2',
            name='identifier',
            field=models.CharField(db_index=True, default='temp', help_text='If from PCGL, inherit. Otherwise created in Katsu.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetv2',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='chord.project'),
        ),
        migrations.AlterField(
            model_name='datasetv2',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dv2', to='chord.project'),
        ),
        migrations.AddConstraint(
            model_name='datasetv2',
            constraint=models.UniqueConstraint(fields=('identifier', 'language'), name='unique_dataset_identifier_per_language'),
        ),
    ]
