# Generated by Django 5.2.11 on 2026-03-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0013_remove_datasetv2_chord_datas_id_327358_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetv2',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datasetv2',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='datasetv2',
            name='schema_version',
        ),
        migrations.RemoveField(
            model_name='datasetv2',
            name='study_context',
        ),
        migrations.RemoveField(
            model_name='datasetv2',
            name='study_status',
        ),
        migrations.RemoveField(
            model_name='datasetv2',
            name='version',
        ),
        migrations.AlterField(
            model_name='datasetv2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasetv2',
            name='language',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
