# Generated by Django 5.2.11 on 2026-03-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0014_remove_datasetv2_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetv2',
            name='id',
        ),
        migrations.AddField(
            model_name='datasetv2',
            name='pk',
            field=models.CompositePrimaryKey('identifier', 'language', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
