# Generated by Django 4.1.1 on 2022-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_v1_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='extra_properties',
            field=models.JSONField(blank=True, help_text='Extra properties that are not supported by current schema.', null=True),
        ),
    ]
