# Generated by Django 2.2.8 on 2019-12-10 21:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the individual.', max_length=200, primary_key=True, serialize=False)),
                ('alternate_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='A list of alternative identifiers for the individual.', null=True, size=None)),
                ('date_of_birth', models.DateField(blank=True, help_text='A timestamp either exact or imprecise.', null=True)),
                ('age', models.CharField(blank=True, help_text='The age or age range of the individual.', max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('UNKNOWN_SEX', 'UNKNOWN_SEX'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER_SEX', 'OTHER_SEX')], help_text='Observed apparent sex of the individual.', max_length=200, null=True)),
                ('karyotypic_sex', models.CharField(choices=[('UNKNOWN_KARYOTYPE', 'UNKNOWN_KARYOTYPE'), ('XX', 'XX'), ('XY', 'XY'), ('XO', 'XO'), ('XXY', 'XXY'), ('XXX', 'XXX'), ('XXYY', 'XXYY'), ('XXXY', 'XXXY'), ('XXXX', 'XXXX'), ('XYY', 'XYY'), ('OTHER_KARYOTYPE', 'OTHER_KARYOTYPE')], default='UNKNOWN_KARYOTYPE', help_text='The karyotypic sex of the individual.', max_length=200)),
                ('taxonomy', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ontology resource representing the species (e.g., NCBITaxon:9615).', null=True)),
                ('active', models.BooleanField(default=False, help_text="Whether this patient's record is in active use.")),
                ('deceased', models.BooleanField(default=False, help_text='Indicates if the individual is deceased or not.')),
                ('race', models.CharField(blank=True, help_text="A code for the person's race.", max_length=200)),
                ('ethnicity', models.CharField(blank=True, help_text="A code for the person's ethnicity.", max_length=200)),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Extra properties that are not supported by current schema', null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
