# Generated by Django 2.2.7 on 2019-12-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='age',
        ),
    ]
