# Generated by Django 2.2.6 on 2019-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_id', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('ontology_id', 'label')},
            },
        ),
    ]
