# Generated by Django 2.2.7 on 2019-12-16 22:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_individual_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='age',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The age or age range of the individual.', null=True),
        ),
    ]
