# Generated by Django 2.2.6 on 2019-10-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_ontology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotypicfeature',
            name='modifier',
        ),
        migrations.AddField(
            model_name='phenotypicfeature',
            name='modifier',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='onset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsets', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phenotypes', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severities', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='body_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_sites', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='zygosity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Ontology'),
        ),
    ]
