# Generated by Django 2.2.6 on 2019-10-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20191003_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='onset',
            new_name='age_of_onset',
        ),
        migrations.AddField(
            model_name='disease',
            name='age_of_onset_ontology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_of_onset_ontologies', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='tumor_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tumor_stages', to='patients.Ontology'),
        ),
    ]
