# Generated by Django 4.2.5 on 2023-10-23 19:04

from django.db import migrations

MCODE_FIELDS = ['comorbid_condition', 'ecog_performance_status', 'ethnicity', 'karnofsky', 'race']

def migrate_mcode_fields(apps, _schema_editor):
    Individual = apps.get_model("patients", "Individual")
    for ind in Individual.objects.all():
        for field in MCODE_FIELDS:
            if field_value := getattr(ind, field):
                ind.extra_properties[field] = field_value

        ind.save()


def reverse_migrate_mcode_fields(apps, _schema_editor):
    Individual = apps.get_model("patients", "Individual")
    for ind in Individual.objects.all():
        for field in MCODE_FIELDS:
              setattr(ind, field, ind.extra_properties.pop(field))
        ind.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_v2_18_0'),
    ]

    operations = [
        migrations.RunPython(migrate_mcode_fields, reverse_migrate_mcode_fields),
        migrations.RemoveField(
            model_name='individual',
            name='comorbid_condition',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='ecog_performance_status',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='karnofsky',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='race',
        ),
    ]
