# Generated by Django 4.2.5 on 2023-10-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_v2_18_0'),
    ]

    # TODO: data migration of removed fields to extra_properties

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='comorbid_condition',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='ecog_performance_status',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='karnofsky',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='race',
        ),
    ]
