# Generated by Django 2.2.6 on 2019-10-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20191003_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalreference',
            name='description',
        ),
    ]
