# Generated by Django 4.1.7 on 2023-03-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_v2_18_0'),
        ('patients', '0004_v3_0_0'),
    ]

    operations = [
    ]
