# Generated by Django 2.2.10 on 2020-03-11 20:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200129_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='comorbid_condition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='One or more conditions that occur with primary condition.', null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='ecog_performance_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Value representing the Eastern Cooperative Oncology Group performance status.', null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='karnofsky',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Value representing the Karnofsky Performance status.', null=True),
        ),
    ]
