# Generated by Django 4.2.6 on 2023-10-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_vitalstatus_remove_individual_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalstatus',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalstatus',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
