# Generated by Django 2.2.6 on 2019-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_externalreference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreference',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
