# Generated by Django 2.2.6 on 2019-10-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_externalreference_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomies', to='patients.Ontology'),
        ),
    ]
