# Generated by Django 4.2.7 on 2023-11-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_v5_0_0'),
        ('patients', '0006_alter_individual_created_alter_individual_updated_and_more'),
    ]

    operations = [
    ]
