# Generated by Django 5.0.9 on 2024-12-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_v8_0_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='active',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='deceased',
        ),
    ]
