# Generated by Django 2.2.6 on 2019-10-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20191003_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='diagnostic_marker',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='hts_file',
        ),
        migrations.AddField(
            model_name='biosample',
            name='diagnostic_markers',
            field=models.ManyToManyField(blank=True, related_name='diagnostic_markers', to='patients.Ontology'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='hts_files',
            field=models.ManyToManyField(blank=True, related_name='biosample_hts_files', to='patients.HtsFile'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='historical_diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histological_diagnoses', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='phenotypic_feature',
            field=models.ManyToManyField(blank=True, to='patients.PhenotypicFeature', verbose_name='phenotypic_features'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='sampled_tissue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampled_tissues', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biosample_taxonomies', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tumor_grades', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='tumor_progression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tumor_progressions', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_taxonomies', to='patients.Ontology'),
        ),
    ]
