# Generated by Django 2.2.6 on 2019-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20191003_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='phenotypic_feature',
        ),
        migrations.AddField(
            model_name='biosample',
            name='phenotypic_features',
            field=models.ManyToManyField(blank=True, to='patients.PhenotypicFeature'),
        ),
    ]
