# Generated by Django 2.2.6 on 2019-10-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20191003_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosample',
            old_name='individual',
            new_name='individual_id',
        ),
        migrations.RenameField(
            model_name='biosample',
            old_name='variant',
            new_name='variants',
        ),
    ]
