# Generated by Django 5.1.13 on 2025-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_v11_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='fts_extra',
            field=models.TextField(blank=True, default=''),
        ),
    ]
