# Generated by Django 5.1.13 on 2025-11-14 16:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_v11_0_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='individual',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('id', 'alternate_ids', 'date_of_birth', 'sex', 'karyotypic_sex', django.db.models.functions.comparison.Cast('gender', models.TextField()), django.db.models.functions.comparison.Cast('taxonomy', models.TextField()), django.db.models.functions.comparison.Cast('time_at_last_encounter', models.TextField()), django.db.models.functions.comparison.Cast('time_at_last_encounter__age', models.TextField()), django.db.models.functions.comparison.Cast('time_at_last_encounter__age_range', models.TextField()), django.db.models.functions.comparison.Cast('vital_status__status', models.TextField()), django.db.models.functions.comparison.Cast('vital_status__time_of_death', models.TextField()), django.db.models.functions.comparison.Cast('vital_status__cause_of_death', models.TextField()), django.db.models.functions.comparison.Cast('vital_status__survival_time_in_days', models.TextField()), django.db.models.functions.comparison.Cast('extra_properties', models.TextField())), name='individual_fts_gin_idx'),
        ),
    ]
