# Generated by Django 5.1.11 on 2025-07-31 19:40

import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_individual_gender_alter_individual_taxonomy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.JSONField(blank=True, help_text='Self-identified gender', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='taxonomy',
            field=models.JSONField(blank=True, help_text='Ontology resource representing the species (e.g., NCBITaxon:9615).', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='individual',
            name='time_at_last_encounter',
            field=models.JSONField(blank=True, help_text='TimeElement of the patient when last encountered.', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='vitalstatus',
            name='cause_of_death',
            field=models.JSONField(blank=True, help_text='Should be left blank if patient not known to be deceased', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='ONTOLOGY_CLASS')]),
        ),
        migrations.AlterField(
            model_name='vitalstatus',
            name='time_of_death',
            field=models.JSONField(blank=True, help_text='Should be left blank if patient not known to be deceased', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='TIME_ELEMENT_SCHEMA')]),
        ),
    ]
