# Generated by Django 2.2.6 on 2019-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20191003_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phenopacket',
            old_name='biosample',
            new_name='biosamples',
        ),
        migrations.RenameField(
            model_name='phenopacket',
            old_name='disease',
            new_name='diseases',
        ),
        migrations.RenameField(
            model_name='phenopacket',
            old_name='hts_file',
            new_name='hts_files',
        ),
        migrations.RenameField(
            model_name='phenopacket',
            old_name='phenotypic_feature',
            new_name='phenotypic_features',
        ),
        migrations.RenameField(
            model_name='phenopacket',
            old_name='variant',
            new_name='variants',
        ),
        migrations.RemoveField(
            model_name='phenopacket',
            name='gene',
        ),
        migrations.AddField(
            model_name='phenopacket',
            name='genes',
            field=models.ManyToManyField(blank=True, to='patients.Gene'),
        ),
    ]
