# Generated by Django 5.2.11 on 2026-02-25 18:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_v13_1_0'),
        ('patients', '0011_individual_fts_extra'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='individual',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='ind_id_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sex'], name='ind_sex_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=django.contrib.postgres.indexes.GinIndex(fields=['karyotypic_sex'], name='ind_karyotypic_sex_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts_extra'], name='ind_fts_extra_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
