# Generated by Django 2.2.6 on 2019-10-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20191003_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='genomic_interpretation',
            new_name='genomic_interpretations',
        ),
    ]
