# Generated by Django 5.2.12 on 2026-03-30 21:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_v13_1_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vitalstatus',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cause_of_death'], name='vs_cause_of_death_idx'),
        ),
    ]
