# Generated by Django 2.2.6 on 2019-10-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20191003_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='alternate_id',
            new_name='alternate_ids',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='external_reference',
            new_name='external_references',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='resource',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='update',
            new_name='updates',
        ),
        migrations.RenameField(
            model_name='phenotypicfeature',
            old_name='phenotype',
            new_name='_type',
        ),
    ]
