# Generated by Django 2.2.6 on 2019-10-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20191003_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='zygosity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zygosities', to='patients.Ontology'),
        ),
    ]
