# Generated by Django 2.2.6 on 2019-10-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20191003_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscnallele',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='spdiallele',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='vcfallele',
            name='variant',
        ),
        migrations.DeleteModel(
            name='HgvsAllele',
        ),
        migrations.DeleteModel(
            name='IscnAllele',
        ),
        migrations.DeleteModel(
            name='SpdiAllele',
        ),
        migrations.DeleteModel(
            name='VcfAllele',
        ),
    ]
