# Generated by Django 2.2.6 on 2019-10-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20191004_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ontology',
            unique_together=set(),
        ),
    ]
