# Generated by Django 2.2.6 on 2019-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20191007_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='id',
        ),
        migrations.RemoveField(
            model_name='htsfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phenopacket',
            name='id',
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='htsfile',
            name='uri',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phenopacket',
            name='phenopacket_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
