# Generated by Django 2.2.6 on 2019-10-08 16:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20191008_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='updates',
        ),
        migrations.AddField(
            model_name='metadata',
            name='updates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
