# Generated by Django 2.2.6 on 2019-10-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20191008_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
