# Generated by Django 2.2.6 on 2019-10-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_delete_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOwnership',
            fields=[
                ('table_id', models.UUIDField(primary_key=True, serialize=False)),
                ('service_id', models.UUIDField()),
                ('data_type', models.CharField(max_length=200)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Dataset')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Biosample')),
            ],
        ),
    ]
