# Generated by Django 2.2.6 on 2019-10-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_tableownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='onset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsets', to='patients.Ontology'),
        ),
        migrations.AlterField(
            model_name='phenotypicfeature',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severities', to='patients.Ontology'),
        ),
    ]
