# Generated by Django 2.2.6 on 2019-10-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20191008_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='individual_id',
        ),
        migrations.AddField(
            model_name='biosample',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Individual'),
        ),
        migrations.RemoveField(
            model_name='phenopacket',
            name='biosamples',
        ),
        migrations.AddField(
            model_name='phenopacket',
            name='biosamples',
            field=models.ManyToManyField(blank=True, to='patients.Biosample'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='phenotypic_features',
        ),
        migrations.AddField(
            model_name='biosample',
            name='phenotypic_features',
            field=models.ManyToManyField(blank=True, to='patients.PhenotypicFeature'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='diagnostic_markers',
        ),
        migrations.AddField(
            model_name='biosample',
            name='diagnostic_markers',
            field=models.ManyToManyField(blank=True, related_name='diagnostic_markers', to='patients.Ontology'),
        ),
        migrations.RemoveField(
            model_name='phenopacket',
            name='hts_files',
        ),
        migrations.AddField(
            model_name='phenopacket',
            name='hts_files',
            field=models.ManyToManyField(blank=True, to='patients.HtsFile'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='hts_files',
        ),
        migrations.AddField(
            model_name='biosample',
            name='hts_files',
            field=models.ManyToManyField(blank=True, related_name='biosample_hts_files', to='patients.HtsFile'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='variants',
        ),
        migrations.AddField(
            model_name='biosample',
            name='variants',
            field=models.ManyToManyField(blank=True, to='patients.Variant'),
        ),
    ]
