# Generated by Django 2.2.6 on 2019-10-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_regenerate_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='tumor_stage',
        ),
        migrations.AddField(
            model_name='disease',
            name='tumor_stage',
            field=models.ManyToManyField(blank=True, to='patients.Ontology'),
        ),
    ]
