# Generated by Django 2.2.6 on 2019-10-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20191015_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenopacket',
            name='subject',
        ),
    ]
