# Generated by Django 2.2.6 on 2019-10-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_remove_phenopacket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenopacket',
            name='subject',
            field=models.ForeignKey(default='dummy', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual'),
            preserve_default=False,
        ),
    ]
