# Generated by Django 2.2.6 on 2019-10-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_remove_phenopacket_phenotypic_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenopacket',
            name='phenotypic_features',
            field=models.ManyToManyField(blank=True, to='patients.PhenotypicFeature'),
        ),
    ]
