# Generated by Django 2.2.6 on 2019-10-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_phenopacket_phenotypic_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenopacket',
            name='genes',
        ),
    ]
