# Generated by Django 2.2.6 on 2019-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_remove_phenopacket_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenopacket',
            name='genes',
            field=models.ManyToManyField(blank=True, to='patients.Gene'),
        ),
    ]
