# Generated by Django 2.2.6 on 2019-10-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_phenopacket_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenopacket',
            name='diseases',
        ),
    ]
