# Generated by Django 2.2.6 on 2019-10-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_remove_phenopacket_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenopacket',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='patients.Disease'),
        ),
    ]
