# Generated by Django 2.2.6 on 2019-10-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_phenopacket_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenopacket',
            name='variants',
        ),
    ]
