# Generated by Django 2.2.6 on 2019-10-28 15:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20191028_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='individual',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='individual',
            name='race',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='individual',
            name='taxonomy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
