# Generated by Django 2.2.6 on 2019-10-28 20:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20191028_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='active',
            field=models.BooleanField(default=False, help_text="Whether this patient's record is in active use."),
        ),
        migrations.AlterField(
            model_name='individual',
            name='address_postal_code',
            field=models.CharField(blank=True, help_text='Postal code for area.', max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.CharField(blank=True, help_text='The age or age range of the individual.', max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='alternate_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='A list of alternative identifiers for the individual.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='A timestamp either exact or imprecise.', null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='deceased',
            field=models.BooleanField(default=False, help_text='Indicates if the individual is deceased or not.'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ethnicity',
            field=models.CharField(blank=True, help_text="A code for the person's ethnicity.", max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_id',
            field=models.CharField(help_text='An arbitrary identifier for the individual.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='karyotypic_sex',
            field=models.CharField(blank=True, choices=[('UNKNOWN_KARYOTYPE', 'UNKNOWN_KARYOTYPE'), ('XX', 'XX'), ('XY', 'XY'), ('XO', 'XO'), ('XXY', 'XXY'), ('XXX', 'XXX'), ('XXYY', 'XXYY'), ('XXXY', 'XXXY'), ('XXXX', 'XXXX'), ('XYY', 'XYY'), ('OTHER_KARYOTYPE', 'OTHER_KARYOTYPE')], help_text='The karyotypic sex of the individual.', max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='race',
            field=models.CharField(blank=True, help_text="A code for the person's race.", max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(blank=True, choices=[('UNKNOWN_SEX', 'UNKNOWN_SEX'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER_SEX', 'OTHER_SEX')], help_text='Observed apparent sex of the individual.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='taxonomy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Ontology resource representing the species (e.g., NCBITaxon:9615).', null=True),
        ),
    ]
