# Generated by Django 2.2.6 on 2019-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_auto_20191028_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='karyotypic_sex',
            field=models.CharField(blank=True, choices=[('UNKNOWN_KARYOTYPE', 'UNKNOWN_KARYOTYPE'), ('XX', 'XX'), ('XY', 'XY'), ('XO', 'XO'), ('XXY', 'XXY'), ('XXX', 'XXX'), ('XXYY', 'XXYY'), ('XXXY', 'XXXY'), ('XXXX', 'XXXX'), ('XYY', 'XYY'), ('OTHER_KARYOTYPE', 'OTHER_KARYOTYPE')], help_text='The karyotypic sex of the individual.', max_length=200, null=True),
        ),
    ]
