# Generated by Django 2.2.10 on 2020-03-09 19:32

import chord_metadata_service.restapi.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_auto_20200129_1537'),
        ('phenopackets', '0004_auto_20200129_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerCondition',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the cancer condition.', max_length=200, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], help_text='Cancer condition type: primary or secondary.', max_length=200)),
                ('body_location_code', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='Code for the body location, optionally pre-coordinating laterality or direction. Accepted ontologies: SNOMED CT, ICD-O-3 and others.', null=True, size=None)),
                ('clinical_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A flag indicating whether the condition is active or inactive, recurring, in remission, or resolved (as of the last update of the Condition). Accepted code system: http://terminology.hl7.org/CodeSystem/condition-clinical', null=True)),
                ('condition_code', django.contrib.postgres.fields.jsonb.JSONField(help_text='A code describing the type of primary or secondary malignant neoplastic disease.')),
                ('date_of_diagnosis', models.DateTimeField(blank=True, help_text='The date the disease was first clinically recognized with sufficient certainty, regardless of whether it was fully characterized at that time.', null=True)),
                ('histology_morphology_behavior', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A description of the morphologic and behavioral characteristics of the cancer. Accepted ontologies:SNOMED CT, ICD-O-3 and others.', null=True)),
                ('subject', models.ForeignKey(help_text='The subject of the study that has a cancer condition.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='GeneticVariantFound',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the genetic variant found.', max_length=200, primary_key=True, serialize=False)),
                ('method', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to indetify the method used to perform the genetic test. Accepted value set: NCIT', null=True)),
                ('variant_found_identifier', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The variation ID assigned by HGVS, for example, 360448 is the identifier for NM_005228.4(EGFR):c.-237A>G (single nucleotide variant in EGFR). Accepted value set: ClinVar.', null=True)),
                ('variant_found_hgvs_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Symbolic representation of the variant used in HGVS, for example, NM_005228.4(EGFR):c.-237A>G for HVGS variation ID 360448.', null=True, size=None)),
                ('variant_found_description', models.CharField(blank=True, help_text='Description of the variant.', max_length=200)),
                ('genomic_source_class', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to indetify the genomic class of the specimen being analyzed.', null=True)),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='GeneticVariantTested',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the genetic variant tested.', max_length=200, primary_key=True, serialize=False)),
                ('method', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to indetify the method used to perform the genetic test. Accepted value set: NCIT', null=True)),
                ('variant_tested_identifier', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The variation ID assigned by HGVS, for example, 360448 is the identifier for NM_005228.4(EGFR):c.-237A>G (single nucleotide variant in EGFR).', null=True)),
                ('variant_tested_hgvs_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Symbolic representation of the variant used in HGVS, for example, NM_005228.4(EGFR):c.-237A>G for HVGS variation ID 360448.', null=True, size=None)),
                ('variant_tested_description', models.CharField(blank=True, help_text='Description of the variant.', max_length=200)),
                ('data_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to indetify positive or negative value for the mutation. Accepted value set: SNOMED CT.', null=True)),
                ('gene_studied', models.ForeignKey(blank=True, help_text='A gene targeted for mutation analysis, identified in HUGO Gene Nomenclature Committee (HGNC) notation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phenopackets.Gene')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='TNMStaging',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the TNM staging.', max_length=200, primary_key=True, serialize=False)),
                ('tnm_type', models.CharField(choices=[('clinical', 'clinical'), ('pathologic', 'pathologic')], help_text='TNM type: clinical or pathological.', max_length=200)),
                ('stage_group', django.contrib.postgres.fields.jsonb.JSONField(help_text='The extent of the cancer in the body, according to the TNM classification system. Accepted ontologies: SNOMED CT, AJCC and others.')),
                ('primary_tumor_category', django.contrib.postgres.fields.jsonb.JSONField(help_text='Category of the primary tumor, based on its size and extent. Accepted ontologies: SNOMED CT, AJCC and others.')),
                ('regional_nodes_category', django.contrib.postgres.fields.jsonb.JSONField(help_text='Category of the presence or absence of metastases in regional lymph nodes. Accepted ontologies: SNOMED CT, AJCC and others.')),
                ('distant_metastases_category', django.contrib.postgres.fields.jsonb.JSONField(help_text='Category describing the presence or absence of metastases in remote anatomical locations. Accepted ontologies: SNOMED CT, AJCC and others.')),
                ('cancer_condition', models.ForeignKey(help_text='Cancer condition.', on_delete=django.db.models.deletion.CASCADE, to='mcode.CancerCondition')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='MedicationStatement',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the medication statement.', max_length=200, primary_key=True, serialize=False)),
                ('medication_code', django.contrib.postgres.fields.jsonb.JSONField(help_text='A code for medication. Accepted code systems:Medication Clinical Drug (RxNorm) and other.')),
                ('termination_reason', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='A code explaining unplanned or premature termination of a course ofmedication. Accepted ontologies: SNOMED CT.', null=True, size=None)),
                ('treatment_intent', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The purpose of a treatment.Accepted ontologies: SNOMED CT.', null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='The start date/time of the medication.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='The end date/time of the medication.', null=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='The date/time the medication was administered.', null=True)),
                ('subject', models.ForeignKey(help_text='Subject of medication statement.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='LabsVital',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the labs/vital tests.', max_length=200, primary_key=True, serialize=False)),
                ('body_height', django.contrib.postgres.fields.jsonb.JSONField(help_text="The patient's height.")),
                ('body_weight', django.contrib.postgres.fields.jsonb.JSONField(help_text="The patient's weight.")),
                ('cbc_with_auto_differential_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Reference to a laboratory observation in the CBC with Auto Differential Panel test. ', null=True, size=None)),
                ('comprehensive_metabolic_2000', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Reference to a laboratory observation in the CMP 2000 test.', null=True, size=None)),
                ('blood_pressure_diastolic', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The blood pressure after the contraction of the heart while the chambers of the heart refill with blood, when the pressure is lowest.', null=True)),
                ('blood_pressure_systolic', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The blood pressure during the contraction of the left ventricle of the heart, when blood pressure is at its highest.', null=True)),
                ('tumor_marker_test', django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology or controlled vocabulary term to indetify tumor marker test.')),
                ('individual', models.ForeignKey(help_text='The individual who is the subject of the tests.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='GenomicsReport',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the genetics report.', max_length=200, primary_key=True, serialize=False)),
                ('test_name', django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology or controlled vocabulary term to identify the laboratory test.Accepted value sets: LOINC, GTR')),
                ('performing_ogranization_name', models.CharField(blank=True, help_text='The name of the organization producing the genomics report.', max_length=200)),
                ('specimen_type', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to indetify the type of material the specimen contains or consists of.Accepted value set: HL7 Version 2 and Specimen Type.', null=True)),
                ('genetic_variant_found', models.ManyToManyField(blank=True, help_text='Records an alteration in the most common DNA nucleotide sequence.', to='mcode.GeneticVariantFound')),
                ('genetic_variant_tested', models.ManyToManyField(blank=True, help_text='A test for a specific mutation on a particular gene.', to='mcode.GeneticVariantTested')),
                ('subject', models.ForeignKey(help_text='Subject of genomics report.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
        migrations.CreateModel(
            name='CancerRelatedProcedure',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the procedure.', max_length=200, primary_key=True, serialize=False)),
                ('procedure_type', models.CharField(choices=[('radiation', 'radiation'), ('surgical', 'surgical')], help_text='Type of cancer related procedure: radion or surgical procedure.', max_length=200)),
                ('code', django.contrib.postgres.fields.jsonb.JSONField(help_text='Code for the procedure performed.')),
                ('occurence_time_or_period', django.contrib.postgres.fields.jsonb.JSONField(help_text='The date/time that a procedure was performed.')),
                ('target_body_site', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='The body location(s) where the procedure was performed.', null=True, size=None)),
                ('treatment_intent', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The purpose of a treatment.', null=True)),
                ('subject', models.ForeignKey(help_text='The patient who has a cancer condition.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
    ]
