# Generated by Django 2.2.10 on 2020-03-11 20:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancercondition',
            name='histology_morphology_behavior',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A description of the morphologic and behavioral characteristics of the cancer. Accepted ontologies: SNOMED CT, ICD-O-3 and others.', null=True),
        ),
        migrations.AlterField(
            model_name='cancercondition',
            name='subject',
            field=models.ForeignKey(help_text='The subject (Patient) of the study that has a cancer condition.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual'),
        ),
        migrations.AlterField(
            model_name='cancerrelatedprocedure',
            name='procedure_type',
            field=models.CharField(choices=[('radiation', 'radiation'), ('surgical', 'surgical')], help_text='Type of cancer related procedure: radion or surgical.', max_length=200),
        ),
        migrations.AlterField(
            model_name='geneticvariantfound',
            name='genomic_source_class',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to identify the genomic class of the specimen being analyzed.', null=True),
        ),
        migrations.AlterField(
            model_name='geneticvariantfound',
            name='method',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to identify the method used to perform the genetic test. Accepted value set: NCIT.', null=True),
        ),
        migrations.AlterField(
            model_name='geneticvarianttested',
            name='data_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to identify positive or negative value forthe mutation. Accepted value set: SNOMED CT.', null=True),
        ),
        migrations.AlterField(
            model_name='geneticvarianttested',
            name='method',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to identify the method used to perform the genetic test. Accepted value set: NCIT.', null=True),
        ),
        migrations.AlterField(
            model_name='genomicsreport',
            name='performing_ogranization_name',
            field=models.CharField(blank=True, help_text='The name of the organization  producing the genomics report.', max_length=200),
        ),
        migrations.AlterField(
            model_name='genomicsreport',
            name='specimen_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='An ontology or controlled vocabulary term to identify the type of material the specimen contains or consists of. Accepted value set: HL7 Version 2 and Specimen Type.', null=True),
        ),
        migrations.AlterField(
            model_name='genomicsreport',
            name='subject',
            field=models.ForeignKey(help_text='Subject (Patient) of genomics report.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual'),
        ),
        migrations.AlterField(
            model_name='genomicsreport',
            name='test_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology or controlled vocabulary term to identify the laboratory test. Accepted value sets: LOINC, GTR.'),
        ),
        migrations.AlterField(
            model_name='labsvital',
            name='cbc_with_auto_differential_panel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Reference to a laboratory observation in the CBC with Auto DifferentialPanel test.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='labsvital',
            name='tumor_marker_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='An ontology or controlled vocabulary term to identify tumor marker test.'),
        ),
        migrations.AlterField(
            model_name='medicationstatement',
            name='medication_code',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='A code for medication. Accepted code systems: Medication Clinical Drug (RxNorm) and other.'),
        ),
        migrations.AlterField(
            model_name='medicationstatement',
            name='termination_reason',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, help_text='A code explaining unplanned or premature termination of a course of medication. Accepted ontologies: SNOMED CT.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='medicationstatement',
            name='treatment_intent',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The purpose of a treatment. Accepted ontologies: SNOMED CT.', null=True),
        ),
        migrations.AlterField(
            model_name='tnmstaging',
            name='stage_group',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='The extent of the cancer in the body, according to the TNM classification system.Accepted ontologies: SNOMED CT, AJCC and others.'),
        ),
    ]
