# Generated by Django 2.2.10 on 2020-03-24 20:25

import chord_metadata_service.restapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200311_1610'),
        ('mcode', '0002_auto_20200311_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancercondition',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='cancerrelatedprocedure',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='genomicsreport',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='medicationstatement',
            name='subject',
        ),
        migrations.CreateModel(
            name='MCodePacket',
            fields=[
                ('id', models.CharField(help_text='An arbitrary identifier for the mcodepacket.', max_length=200, primary_key=True, serialize=False)),
                ('cancer_condition', models.ForeignKey(blank=True, help_text="An Individual's cancer condition.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcode.CancerCondition')),
                ('cancer_related_procedures', models.ManyToManyField(blank=True, help_text='A radiological or surgical procedures addressing a cancer condition.', to='mcode.CancerRelatedProcedure')),
                ('genomics_report', models.ForeignKey(blank=True, help_text='A genomics report associated with an Individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcode.GenomicsReport')),
                ('medication_statement', models.ForeignKey(blank=True, help_text='Medication treatment addressed to an Individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcode.MedicationStatement')),
                ('subject', models.ForeignKey(help_text='An individual who is a subject of mcodepacket.', on_delete=django.db.models.deletion.CASCADE, to='patients.Individual')),
            ],
            bases=(models.Model, chord_metadata_service.restapi.models.IndexableMixin),
        ),
    ]
