# Generated by Django 4.2.5 on 2023-10-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0006_v4_0_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancergeneticvariant',
            name='gene_studied',
        ),
        migrations.RemoveField(
            model_name='cancerrelatedprocedure',
            name='reason_reference',
        ),
        migrations.RemoveField(
            model_name='genomicsreport',
            name='genetic_specimen',
        ),
        migrations.RemoveField(
            model_name='genomicsreport',
            name='genetic_variant',
        ),
        migrations.RemoveField(
            model_name='genomicsreport',
            name='genomic_region_studied',
        ),
        migrations.RemoveField(
            model_name='labsvital',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='cancer_condition',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='cancer_related_procedures',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='genomics_report',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='medication_statement',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mcodepacket',
            name='tumor_marker',
        ),
        migrations.RemoveField(
            model_name='tnmstaging',
            name='cancer_condition',
        ),
        migrations.DeleteModel(
            name='CancerCondition',
        ),
        migrations.DeleteModel(
            name='CancerGeneticVariant',
        ),
        migrations.DeleteModel(
            name='CancerRelatedProcedure',
        ),
        migrations.DeleteModel(
            name='GeneticSpecimen',
        ),
        migrations.DeleteModel(
            name='GenomicRegionStudied',
        ),
        migrations.DeleteModel(
            name='GenomicsReport',
        ),
        migrations.DeleteModel(
            name='LabsVital',
        ),
        migrations.DeleteModel(
            name='MCodePacket',
        ),
        migrations.DeleteModel(
            name='MedicationStatement',
        ),
        migrations.DeleteModel(
            name='TNMStaging',
        ),
    ]
