# Generated by Django 4.2.1 on 2023-06-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0006_mcodepacket_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcodepacket',
            name='table',
        ),
    ]
