# Generated by Django 2.2.13 on 2020-06-11 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0006_auto_20200610_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicsreport',
            name='issued',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time this report was issued.'),
        ),
    ]
