# Generated by Django 2.2.13 on 2020-06-11 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0007_auto_20200610_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicsreport',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 3, 20, 6, 606068, tzinfo=utc), help_text='The date/time this report was issued.'),
        ),
    ]
