# Generated by Django 2.2.13 on 2020-06-18 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0018_auto_20200601_1708'),
        ('mcode', '0008_auto_20200610_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcodepacket',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chord.Table'),
        ),
        migrations.AlterField(
            model_name='genomicsreport',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 17, 18, 39, 482556, tzinfo=utc), help_text='The date/time this report was issued.'),
        ),
    ]
