# Generated by Django 2.2.13 on 2020-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '0010_auto_20200618_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcodepacket',
            name='medication_statement',
        ),
        migrations.AddField(
            model_name='mcodepacket',
            name='medication_statement',
            field=models.ManyToManyField(blank=True, help_text='Medication treatment addressed to an Individual.', to='mcode.MedicationStatement'),
        ),
    ]
