# Generated by Django 2.2.6 on 2019-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableownership',
            name='service_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tableownership',
            name='table_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
