# Generated by Django 2.2.19 on 2021-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0001_v1_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data_type',
            field=models.CharField(choices=[('experiment', 'experiment'), ('phenopacket', 'phenopacket'), ('mcodepacket', 'mcodepacket')], max_length=30),
        ),
    ]
