# Generated by Django 2.2.6 on 2019-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0002_auto_20191113_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableownership',
            name='service_artifact',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tableownership',
            name='service_id',
            field=models.UUIDField(),
        ),
    ]
