# Generated by Django 2.2.28 on 2022-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0002_auto_20210409_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dats_file',
            field=models.TextField(blank=True, help_text='Content of a valid DATS file, in JSON format, that specifies the dataset provenance.'),
        ),
    ]
