# Generated by Django 2.2.7 on 2019-11-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0003_auto_20191113_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='chord.Project'),
        ),
    ]
