# Generated by Django 2.2.9 on 2020-01-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0003_dataset_field_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='field_links',
            new_name='field_link_sets',
        ),
    ]
