# Generated by Django 4.1.1 on 2023-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0003_alter_dataset_acknowledges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data_type',
            field=models.CharField(choices=[('experiment', 'experiment'), ('phenopacket', 'phenopacket')], max_length=30),
        ),
    ]
