# Generated by Django 2.2.9 on 2020-01-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0004_auto_20200123_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='field_link_sets',
            new_name='linked_field_sets',
        ),
    ]
