# Generated by Django 4.2.1 on 2023-08-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('chord', '0006_remove_tableownership_dataset'), ('chord', '0007_delete_table_delete_tableownership')]

    dependencies = [
        ('phenopackets', '__latest__'),
        ('chord', '0005_v3_0_0'),
        ('mcode', '__latest__'),
        ('experiments', '__latest__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableownership',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableOwnership',
        ),
    ]
