# Generated by Django 4.2.1 on 2023-06-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcode', '__latest__'),
        ('experiments', '__latest__'),
        ('phenopackets', '__latest__'),
        ('chord', '0006_remove_tableownership_dataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableOwnership',
        ),
    ]
