# Generated by Django 4.2.7 on 2024-01-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0006_v4_0_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dats_file',
            field=models.JSONField(blank=True, null=True, help_text='Content of a valid DATS file, in JSON format, that specifies the dataset provenance.'),
        )
    ]
