# Generated by Django 2.2.9 on 2020-02-18 21:15

import chord_metadata_service.chord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0008_dataset_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='version',
            field=models.CharField(blank=True, default=chord_metadata_service.chord.models.version_default, help_text='A release point for the dataset when applicable.', max_length=200),
        ),
    ]
