# Generated by Django 5.1.13 on 2025-10-15 15:18

import chord_metadata_service.chord.models
import chord_metadata_service.restapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('chord', '0010_dataset_conditions_of_access_alter_dataset_created_and_more')]

    dependencies = [
        ('chord', '0009_v10_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='conditions_of_access',
            field=models.TextField(blank=True, default='', help_text='The data access requests link(s), as defined in https://schema.org/conditionsOfAccess'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='discovery',
            field=chord_metadata_service.chord.models.DiscoveryJSONField(blank=True, help_text='Discovery configuration', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='DISCOVERY_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='discovery',
            field=chord_metadata_service.chord.models.DiscoveryJSONField(blank=True, help_text='Discovery configuration', null=True, validators=[chord_metadata_service.restapi.validators.JsonSchemaValidator(formats=None, schema_ref='DISCOVERY_SCHEMA')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
