# Generated by Django 2.2.11 on 2020-03-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0009_auto_20200218_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableownership',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_ownership', to='chord.Dataset'),
        ),
    ]
