# Generated by Django 5.2.11 on 2026-03-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0010_v11_0_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetV2',
            fields=[
                ('identifier', models.CharField(db_index=True, help_text='If from PCGL, inherit. Otherwise created in Katsu.', max_length=128)),
                ('language', models.CharField(db_index=True, max_length=8)),
                ('pk', models.CompositePrimaryKey('identifier', 'language', blank=True, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('release_date', models.DateField(db_index=True)),
                ('last_modified', models.DateField(db_index=True)),
                ('data', models.JSONField(help_text='Full DatasetModel payload validated by Pydantic before saving.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dv2', to='chord.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
