# Generated by Django 5.2.11 on 2026-02-23 15:28

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0010_v11_0_0'),
    ]

    operations = [TrigramExtension()]
