# Generated by Django 2.2.12 on 2020-05-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0010_auto_20200309_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='acknowledges',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='alternate_identifiers',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='distributions',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='linked_field_sets',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='primary_publications',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='related_identifiers',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='spatial_coverage',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='types',
        ),
    ]
