# Generated by Django 2.2.12 on 2020-05-15 21:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_auto_20200515_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='acknowledges',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The grant(s) which funded and supported the work reported by the dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='alternate_identifiers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Alternate identifiers for the dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='citations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The publication(s) that cite this dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='creators',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The person(s) or organization(s) which contributed to the creation of the dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Relevant dates for the datasets, a date must be added, e.g. creation date or last modification date should be added.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dimensions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The different dimensions (granular components) making up a dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='distributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The distribution(s) by which datasets are made available (for example: mySQL dump).'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Tags associated with the dataset, which will help in its discovery.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='licenses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The terms of use of the dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='linked_field_sets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Data type fields which are linked together.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='primary_publications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The primary publication(s) associated with the dataset, usually describing how the dataset was produced.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='related_identifiers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Related identifiers for the dataset.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='spatial_coverage',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='The geographical extension and span covered by the dataset and its measured dimensions/variables.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='types',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='A term, ideally from a controlled terminology, identifying the dataset type or nature of the data, placing it in a typology.'),
        ),
    ]
