# Generated by Django 5.2.10 on 2026-01-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_alter_dataset_project_datasetv2'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "chord_datasetv2" RENAME COLUMN "pcgl_status" TO "study_status";',
                    reverse_sql='ALTER TABLE "chord_datasetv2" RENAME COLUMN "study_status" TO "pcgl_status";',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "chord_datasetv2" RENAME COLUMN "pcgl_context" TO "study_context";',
                    reverse_sql='ALTER TABLE "chord_datasetv2" RENAME COLUMN "study_context" TO "pcgl_context";',
                ),
            ],
            state_operations=[],
        ),
    ]
