# Generated by Django 5.2.12 on 2026-03-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0011_datasetv2'),
        ('chord', '0011_v13_1_0'),
    ]

    operations = [
    ]
