# Generated by Django 5.2.12 on 2026-03-25 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0012_merge_0011_datasetv2_0011_v13_1_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, help_text='If from PCGL, inherit. Otherwise created in Katsu.', max_length=128),
        ),
    ]
