# Generated by Django 5.2.12 on 2026-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0013_alter_datasetv2_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='en', max_length=8),
        ),
    ]
