# Generated by Django 5.2.12 on 2026-03-29 21:16
# Modified to use IF EXISTS guards — the dev DB may already have language/composite-PK removed.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0014_alter_datasetv2_language'),
    ]

    operations = [
        # Drop language column; IF EXISTS guards against it already being gone in dev.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE chord_datasetv2 DROP COLUMN IF EXISTS language;",
                    reverse_sql=(
                        "ALTER TABLE chord_datasetv2 "
                        "ADD COLUMN language character varying(8) NOT NULL DEFAULT 'en';"
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name='datasetv2', name='language'),
            ],
        ),

        # Remove composite PK pseudo-field from state; fix the actual PK constraint in the DB.
        # The DROP/ADD is safe to re-run: DROP IF EXISTS is a no-op if already gone,
        # and ADD PRIMARY KEY is skipped if identifier is already the PK.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            ALTER TABLE chord_datasetv2 DROP CONSTRAINT IF EXISTS chord_datasetv2_pkey CASCADE;
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.table_constraints
                                WHERE table_name = 'chord_datasetv2'
                                  AND constraint_type = 'PRIMARY KEY'
                            ) THEN
                                ALTER TABLE chord_datasetv2 ADD PRIMARY KEY (identifier);
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name='datasetv2', name='pk'),
                migrations.AlterField(
                    model_name='datasetv2',
                    name='identifier',
                    field=models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        help_text='If from PCGL, inherit. Otherwise created in Katsu.',
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),

        # Create the translation table — always needs to run.
        migrations.CreateModel(
            name='DatasetV2Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=8)),
                ('data', models.JSONField(help_text='Full ProjectScopedDatasetModel payload for this language.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='translations',
                    to='chord.datasetv2',
                )),
            ],
            options={
                'unique_together': {('dataset', 'language')},
            },
        ),
    ]
