# Generated by Django 6.0.5 on 2026-09-02 20:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0015_rename_datasetv2'),
        ('resources', '0002_v2_14_0'),
    ]

    operations = [
        # Enables the `unaccent()` SQL function, used by the catalogue search endpoint for
        # diacritic-stripped substring matching (mirrors the client-side behaviour it replaces).
        UnaccentExtension(),
        migrations.AddField(
            model_name='dataset',
            name='domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='keyword_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='license_label',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='privacy',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='program_name',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='study_context',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='study_status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='taxa_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['domain'], name='chord_datas_domain_0d4664_gin'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['taxa_labels'], name='chord_datas_taxa_la_122443_gin'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keyword_labels'], name='chord_datas_keyword_1cda5f_gin'),
        ),
    ]
