# Generated by Django 6.0.4 on 2026-05-20 18:58

import chord_metadata_service.chord.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0018_datasetv2_additional_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetv2',
            name='discovery',
            field=chord_metadata_service.chord.models.DiscoveryJSONField(blank=True, help_text='Dataset-level discovery configuration.', null=True),
        ),
    ]
