name: Check if all migrations have been performed
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+[-[\w\d]*]?

jobs:
  check-migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/bento-platform/bento_postgis_dist:2025.01.28
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Install Python dependencies
        run: poetry install
      - name: Install GeoDjango Apt dependencies
        run: sudo apt-get update -y && sudo apt-get install -y binutils gdal-bin libproj-dev gdal-bin
      - name: Check for missed migrations
        env:
          DJANGO_SETTINGS_MODULE: chord_metadata_service.metadata.settings
        run: |
          export POSTGRES_USER="postgres" && export POSTGRES_PASSWORD="postgres" && export POSTGRES_PORT=5432
          poetry run ./manage.py makemigrations --check