name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - 'features/**'
      - develop
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    services:
      postgres:
        image: ghcr.io/bento-platform/bento_postgis_dist:2026.07.27
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: python -m pip install poetry
    - name: Install Python dependencies
      run: poetry install
    - name: Install GeoDjango Apt dependencies
      run: sudo apt-get update -y && sudo apt-get install -y binutils gdal-bin libproj-dev gdal-bin
    - name: Test
      run: |
        export POSTGRES_USER="postgres" && export POSTGRES_PASSWORD="postgres" && export POSTGRES_PORT=5432
        poetry run coverage run --branch ./manage.py test
        poetry run coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        verbose: true
